part of 'languages.dart';

const Map<String, String> _koKR = {
  'guide_title_1': '슈퍼세이브 외상거래 설명회',
  'guide_line_1_1': '장소\t서울시 송파구 송파대로 167,\n문정역 테라타워 A동 1303호',
  'guide_line_1_2': '일정\t격주로 진행되오니 자세한 설명회 일정은\n고객센터로 문의하시기 바랍니다.',
  'guide_line_1_3': '강의 소요 시간\t 2~3시간',
  'guide_title_2': '엠스퀘어\n커뮤니티\n전국 사무실 ',
  'guide_line_2_1': '일산\t고양시 일산 서구 중앙로 1765 1층\n010-7987-5995',
  'guide_line_2_2': '광진구\t서울시 광진구 능동로7 한강파크빌팅 314호\n010-4965-3910',
  'guide_line_2_3': '시흥\t시흥시 협력로 281 메가폴리스 C동 118호\n010-3731-7553',
  'guide_line_2_4': '당진\t충남 당진시 읍내동 531-4 벤처위크 201호\n010-8567-8084',
  'guide_line_2_5': '대전\t대전시 서구 탄방로26 수펠리스 204호\n010-2825-8652',
  'guide_line_2_6': '광주\t광주시 서구 상무평화로 89 413호\n010-3104-2468',
  'guide_line_2_7':
  '속초\t속초시 중앙로 121번길 28 센텀파크\n롯데시네마 134호\n010-7621-5856',
  'guide_line_2_8':
  '수원\t수원시 영통구 삼성로 253 에이스스마트\n영통지식산업센터 914호\n010-6654-8523',
  'guide_line_2_9':
  '용인\t용인시 기흥구 동백죽전대로 341\n동백메디슨타워 B104호\n010-4013-0984',
  'guide_line_2_10': '포항\t포항시 북구 이동로69 득량빌딩 402호\n010-3500-8551',
  'guide_line_2_11': '부산\t부산시 진구 동성로137\n서면동원오피스텔 1202호\n010-2780-8699',
  'guide_line_2_12':
  '창원\t창원시 의창구 사림동 161-1 현대\n썬앤빌더스퀘어 F동 203호\n010-3747-1747/ 070-8657-4717',
  'guide_line_2_13': '광양\t전남 광양시 구마길 61 2층\n010-3993-2667',
  'guide_line_2_14': '세종\t세종시 나성동 792 NS타워 805호\n010-6425-8819',
  'guide_line_2_15': '진주\t진주시 충무공동 69-3 윙스타워 B동 1104호\n010-9301-0803',
  'guide_line_2_16': '사천\t사천시 정동면 옥산로 50-53 매화빌 2층\n010-3780-8215',
  'guide_title_3': '슈퍼세이브 신청 절차',
  'home_ban_title': '전세계 최초',
  'home_ban_subtitle': '블록체인 실물경제 기반 코인 외상거래 플랫폼',
  'participation_complete_first': '지금부터 SUPER SAVE 에\n참여해 볼까요?',
  'participation_complete_second': '아래 SUPER SAVE 참여하기를 눌러주세요!',
  'join_super_save': 'SUPER SAVE 참여하기',
  'cash_transfer_capture_file_missing': '현금 이체 캡처 파일 누락.',
  'coin_transfer_capture_file_missing': '코인 전송 캡처 파일이 누락되었습니다.',
  'total_percentage_cannot_be_more_than_100': '총 백분율은 100% 이하여야 합니다.',
  'new_balance': '적립후',
  'previous_balance': '적립전',
  'reason': '이유',
  'this_transaction_old_than_card_added': '이 트랙잭션은 카드추가전 내용입니다.',
  'this_transaction_cash_dispenser_service': '이 거래는 현금 지급기 서비스입니다.',
  'this_transaction_was_mined_by_another_user':
  '이 트랜잭션은 다른 사용자가 채굴한 것입니다.',
  'mining_time_is_not_within_threshold': '채굴 시간이 임계값 기간 내에 있지 않습니다.',
  'skip': '다음에 하기',
  'skip_phone': '간편 핸드폰 인증 건너뛰기',
  'skip_phone_msg': '건너뛰는 경우, P2U 에어드랍을 받으려면 SUPER SAVE 등록이 승인되어야 합니다.',
  'system_problem': '일부 서비스에 문제가 있습니다',
  'code': '암호',
  'reported': '신고됨',
  'verify': '확인하다',
  'verify_email': '이메일 확인하기',
  'verify_phone': '전화 번호 확인하기',
  'phone': '전화 번호',
  'email': '이메일',
  'mining_failed': '채굴 실패',
  'p2u_mining_not': 'P2U 채굴이 완료되지 않았습니다!',
  'card_issue': '@cardName에 문제가 있습니다. 채굴을 계속하려면 먼저 이 문제를 해결해야 합니다.',
  'i_read': '읽고 이해했습니다',
  'you_are_corporate_member': '귀하는 기업 회원입니다.',
  'you_are_individual_member': '귀하는 개인 회원입니다.',
  'account_holder_name': '계좌 명의',
  'enter_account_holder_name': '계좌 소유자의 이름을 입력하세요',
  'person_charge_number': '담당자 연락처',
  'enter_name': '이름',
  'phone_number_must_be_11_digits': '전화번호는 11자리 여야 합니다',
  'member_type': '회원 유형',
  'indv_member': '개인 회원',
  'corp_member': '단체',
  'corp_popup': '법인회원은 개인거래에 접근할 수 없습니다.',
  'indv_n_corp_member': '개인 회원 / 단체',
  'mined_by': '채굴자',
  'transaction_draft_tooltip': '누락된 P2U 수입을 포함한 모든 정보를 확인할 수 있습니다.',
  'mining_denied': '채굴이 거부되었습니다!',
  'missed_threshold_period': '채굴 타이밍을 놓쳤습니다!',
  'company_policy': '회사정책',
  'use_inquiry': '궁금하신 사항은 1:1문의 메뉴를 이용해주세요.',
  'details': '세부',
  'card_number': '카드번호',
  'store': '스토어',
  'mining_percentage': '채굴 퍼센트',
  'earned_p2u': '얻은 P2U',
  'threshold': '기한',
  'day(s)': '일(들)',
  'payment_status': '결제상태',
  'mining_threshold': '채굴기한',
  'paid': '유료',
  'refund': '환불',
  'affiliated': '제휴',
  'not_affiliated': '비제휴',
  'enable_fingerprint_auth': '지문 인증 활성화',
  'finger_auth_enabled': '지문 인증이 활성화되었습니다.',
  'finger_auth_fail': '지문인증이 취소되었습니다',
  'forgot_pass': '비밀번호를 잊으 셨나요?',
  'reset_pass_header_text': '비밀번호를 재설정하려면 새 비밀번호와 이메일로 전송된 OTP를 입력하세요.',
  'reset_pass_header_text_phone':
  '비밀번호를 재설정하려면 새 비밀번호와 휴대폰으로 전송된 OTP를 입력합니다.',
  'enter_6_digit_otp': 'OTP 6자리를 입력하세요',
  'reset_password': '거래 비밀번호 재설정',
  'apply': '신청하기',
  'discount': '할인율',
  'add_payment_method': '⏳ 카드 연결하기',
  'add_payment_method_error': '카드 연결하기',
  'request_id_copied': '요청 ID가 복사되었습니다.',
  'request_id': '요청 ID',
  'super_save_ownership_received': 'SUPER SAVE 소유권을 성공적으로 받았습니다.',
  'super_save_transfer_success': 'SUPER SAVE 소유권 이전이 성공적으로 완료되었습니다.',
  'enter_valid_email_address': '유효한 이메일 주소를 입력하세요',
  'email_address_cannot_be_empty': '이메일 값은 비워둘 수 없습니다.',
  'transfer_of_ownership_super_save_request':
  '그러면 SUPER SAVE 요청의 소유권이 새 사용자에게 이전됩니다.',
  'new_user_email': '신규 사용자 이메일',
  'un_authorized': '승인되지 않았습니다\n다시 로그인해 주세요.',
  'enter_email_address': '이메일 주소를 입력하세요',
  'submit': '제출하기',
  'transfer_ownership': '소유권 이전',
  'metastar_clients': '메타스타 고객사',
  'waiting': '대기 중',
  'complete_buying': '@token 구매 완료',
  'buy_token': '@token 구매',
  'sell_token': '@token 판매',
  'no_p2p_orders': '@token에 대한 @type 주문이 없습니다.',
  'p2p_order_conv': '@txToken당 @rate @token',
  'complete_p2p_trade': 'P2P 거래 완료',
  'transfer_to_your_accnt': '지갑으로 이체됩니다.',
  'select_wallet_to_pay': '결제할 지갑 선택',
  'connect_wallet_to_pay': '결제할 지갑 연결',
  'you_will_pay': '결제합니다',
  'with_your_wallet': '지갑으로 결제합니다.',
  'amount_n_fee': '(금액+수수료)',
  'promotion_period': '프로모션 기간입니다!',
  'fee_will_not_be_charged': '\n수수료는 부과되지 않습니다.',
  'you_need_pay': '당신은 지불해야',
  'a': 'ㅏ',
  'service_fee': '@val% 서비스 수수료',
  'of_amnt_4_tx': '\n거래에 대한 @token 금액입니다.',
  'will_add_to_amnt': '귀하가 지불할\n@token 금액에 추가됩니다.',
  'complete': '완성한',
  'enter_wallet_address_for_p2p_sell': '@token을 받을\n 지갑 주소를 입력하세요:',
  'enter_wallet_address': '지갑 주소 입력',
  'will_be_charged_from_bal': '@token 잔액에서\n요금이 청구됩니다',
  'continue': '계속하다',
  'today': '오늘',
  'wallet_withdrawal_completed': '@token 지갑 출금을 완료하세요',
  'notification_save': '저장',
  'tx_already_done': '이미 완료된 거래',
  'points': '포인트',
  'current_location': '현재 위치',
  'location_permission': '위치 권한',
  'no_img_avail': '사용 가능한 이미지가 없습니다.',
  'location': '위치',
  'store_near_your_location': '현재 위치 근처에 매장',
  'stores_in_city': '@city에 있는 매장',
  'no_stores_found': '매장을 찾을 수 없음',
  'search_by_address': '이름으로 검색',
  'select_city': '시/군을 선택하세요',
  'city': '시/군을',
  'search_city': '시/군 선택하세요',
  'all_cities': '모든 도시',
  'city_not_found': '도시를 찾을 수 없음',
  'copied': '복사됨',
  'bio_disable_fail': '지문을 비활성화하지 못했습니다.',
  'bio_disable_success': '지문 성공 비활성화',
  'set_bio_auth': '지문 인증 사용',
  'select_wallet': '지갑 선택',
  'gps_required': 'GPS 필요',
  'no_store_found': '매장을 찾을 수 없습니다',
  'gps_msg': '가까운 매장을 검색하시려면 GPS를 켜주세요.',
  'restart_now': '지금 다시 시작',
  'update_avail': '새로운 업데이트 준비',
  'ota_msg': '앱이 버전 @version 으로 성공적으로 업데이트되었습니다. 새 버전을 사용하려면 다시 시작하세요.',
  'User rejected the transaction': '귀하는 거래를 거부했습니다.',
  'User rejected methods': '연결 요청을 거부하셨습니다.',
  'tx_req_sent_check_wallet': '거래요청이 전송되었습니다. 지갑을 확인해 주세요.',
  'tx_in_progress': '거래 진행 중',
  'wallet_not_exist': '해당 지갑이 없습니다',
  'super_save_tx': '슈퍼 세이브 거래',
  'search': '검색',
  'other_wallets': '다른 지갑...',
  'wallet_connection': '@token 월렛 연결',
  'tx_fail': '거래가 실패했습니다',
  'tx_success': '트랜잭션 성공',
  'tx_id_received': '거래 ID 수신됨.',
  'btn_desc': '버튼설명',
  'resident_registration': '거주자 등록',
  'foreign_registration': '외국인 등록',
  'reg_only_seven_digits': '등록에는 7자리 숫자만 있어야 합니다.',
  'plz_select_your_country': '국가를 선택하십시오',
  'plz_select_country_code': '국가 코드를 선택하십시오',
  'wallet_withdrawal': '지갑 인출',
  'select_wallet_for_tx': '트랜잭션을 위한 지갑 선택',
  'and': '와',
  'plz_send_msq_for_credit_sale':
  '외상매도를 신청한@other@and @deposit_token를 보내주세요.',
  'plz_send_deposit_for_credit_sale':
  '외상매도를 신청한 @deposit_token @num_of_deposit_token를 보내세요 외상매도 @total_payout_amount @payment_currency을 승인받습니다.',
  'plz_send_deposit_for_super_save':
  '외상매도 신청한 @deposit_token @num_of_deposit_token를 보내세요 외상매도대금 @total_payout_amount @payment_currency을 승인받습니다.',
  'participate_wallet_address': '@token 입금주소',
  'enter_transmit_txid': '@token Transaction Hash 입력',
  'no_image_found': '이미지를 찾을 수 없습니다',
  'credit_sale_tool_tip':
  '가격은 OTC 시장에 따라 다르며 블록 거래 솔루션으로 인해 변경될 수 있습니다.',
  'change': '변경',
  'go_back': '돌아가기',
  'con_success': '연결 성공',
  'con_fail': '연결 실패',
  'wallet_con_success': '월렛 연결 성공',
  'wallet_con_req': '월렛 연결 요청',
  'wallet_con_req_done': '월렛 연결 요청이 이미 완료되었습니다.',
  'wallet_con_req_received': '님이 지갑 연결을 요청했습니다',
  'wallet_con_req_warning': '사용자가 올바른지 확인하세요.',
  'currency': '통화',
  'default': '디폴트',
  'change_currency': '통화 변경',
  'change_token': '토큰 변경',
  'deposit_wallet': '입금 월',
  'plz_provide_reason_txtbox': '텍스트 상자에 이유를 입력하십시오',
  'charge': '수수료',
  'bank_fee': '수수료',
  'new_connected_wallet_added': '새로운 연결된 지갑이 추가되었습니다.',
  'wallet_deleted': '연결된 지갑이 성공적으로 삭제되었습니다.',
  'my_connected_wallets': '내 연결된 지갑',
  'add_connected_wallet': '연결된 월렛 추가',
  'connected_wallet': '커넥티드 지갑',
  'delete_wallet': '지갑 삭제',
  'main_wallet_not_del': '메인 지갑은 삭제할 수 없습니다.',
  'set_main_wallet': '메인 지갑으로 설정',
  'main_connected_wallet_changed': '메인 연동 지갑 변경',
  'pls_reg_a_wallet': '지갑을 등록해주세요.',
  'wallet_type': '월렛 종류',
  'wallet_id': '지갑 주소',
  'wallet_balance': '월렛 잔액',
  'enter_your_wallet': '지갑을 입력하십시오',
  'wallet_id_length_check':
  '유효한 USDT (Polygon Network) 지갑 주소를 입력해야 합니다.',
  'add_wallet': '지갑 추가',
  'wrng_wallet_id': '지갑 주소가 잘못되었습니다.',
  'align_area_20': '↖️ 카드를 박스 영역에 맞춰주세요.',
  'box_19': '↕️ ↔️ 박스 주변을 맞춰주세요.',
  'hold_on_here': '👀 여기서 버텨봐',
  'its_done': '🆗✅ 다 되었습니다',
  'pic_taken': '✅찍은 사진',
  'pic_selected': '✅ 사진 선택',
  'invalid_qr_code': '유효하지 않은 QR 코드',
  'msq_lock_vol': '현황',
  'otc_msqx_market_cap': 'MSQ OTC, MSQX 시가총액',
  'description': '설명',
  's_trust_mem_price': '슈퍼트러스트 회원가 1@token=@amount @currency',
  'p2u_field_label': '외상매도 신청 P2U 수량',
  'otc_msqx_market_cap_tooltip':
  '장외거래 시가총액\nMSQ OTC 보유 시가총액 + MSQX 보유 시가총액',
  'g_quantity': '기업 보유 수량',
  'current_price': '현재 가격',
  'g_market_cap': '기업 보유 시가총액',
  'otc_market_cap': 'OTC 현재 가격',
  'otc_market_cap_tooltip': '장외거래 현재가격',
  'otc_g_market_cap': 'MSQ, MSQX 기업 보유 시가총액 ',
  'otc_g_market_cap_tooltip': 'MSQ 소유 시가총액 + MSQX 소유 시가총액',
  'coming_soon': '출시 예정',
  'capture_the_image_before': '전에 이미지를 캡처하십시오',
  'captured_image': '캡처된 이미지',
  'fail': '실패하다',
  'put_the_card_in_the_box': '상자에 카드를 넣어주세요',
  'there_is_image_21': '선택한 이미지에 ID 카드가 없습니다.',
  'transfer_credit': '@token 전송하기',
  'enter_recipient_mail': '수신자 이메일 입력',
  'enter_your_amount': '금액을 입력하세요',
  'token_transferred': '전송된 토큰',
  'token_not_transferred': '토큰이 전송되지 않음',
  'alert': '경보',
  'please_unfold': '카메라를 사용하려면 휴대전화를 펴세요.',
  'select_photo': '사진 선택',
  'monday': '월요일',
  'tuesday': '화요일',
  'wednesday': '수요일',
  'thursday': '목요일',
  'friday': '금요일',
  'saturday': '토요일',
  'sunday': '일요일',
  'january': '1월',
  'february': '2월',
  'march': '3월',
  'april': '4월',
  'may': '5월',
  'june': '6월',
  'july': '7월',
  'august': '8월',
  'september': '9월',
  'october': '10월',
  'november': '11월',
  'december': '12월',
  'won_transfer_title': '@bankname 로\n1원을 보냈습니다',
  'confirm_won_auth_title': '인증번호 3자리를 입력 해주세요\n(MSQ 빼고 숫자만 입력)',
  'verification_number': '인증 번호',
  'authenticate_with_different_account': '다른 계좌로 인증',
  'enter_verification_number': '3자리 인증번호',
  'supersave_registration_at_add_bank_account':
  '은행 계좌를 추가하려면 슈퍼 세이브 등록이 필요합니다.',
  'otp_length_warning': '인증 번호는 3자리 숫자여야 합니다.',
  '100_million_krw': '+1억원',
  '100_million_krw_br': '+1\n억원',
  '10_million_krw': '+1,000만원',
  '10_million_krw_br': '+1,000\n만원',
  '10k_usdt': '+10000 USDT',
  '100k_usdt': '+100000 USDT',
  '100_thousand_krw': '+10만원',
  '100_thousand_krw_dialog': '+10만원',
  '100_thousand_krw_br': '+10\n만원',
  '100_thousand_krw_dialog_br': '+10\n만원',
  '1_million_krw': '+100만원',
  '1_million_krw_br': '+100\n만원',
  '1_k_usdt': '+1000 USDT',
  '100_usdt': '+100 USDT',
  '211_88th_seoul_18': '서울시 송파구 송파대로 167, 에이동 917호',
  'x_days_y_perc': '@x일(@y%)',
  'Amount': '수량',
  'entitlement_amount': '권리금액',
  'Buy': '구입하다',
  'change_log': '변경 로그',
  'Buying': '사다',
  'Enter_the_amount_to_swap': '교환할 금액을 입력하세요.',
  'Fee': '요금',
  'My_Assets': '내 자산',
  'Price': '가격',
  'Sell': '팔다',
  'Selling': '팔다',
  'Token': '토큰',
  'Tokens': '토큰',
  'total_balance_in': '총 잔액',
  'user_canceled': '본인이 신청 취소',
  'accept': '수락',
  'sendersut': '발송자',
  'auto': '자동',
  'manual': '수동',
  'accept_pass_agreement': '비밀번호 분실 동의에 동의합니다',
  'account': '계정',
  'account_balance': '계좌잔액',
  'account_holder': '예금주',
  'account_number': '계좌번호',
  'account_numbers_length_warning': '계좌 번호는 11~16자리여야 합니다.',
  'account_registration': '계좌 등록',
  'add_card': '카드 추가하기',
  'add_card_info': '카드 연결하기',
  'add_new_platform': '새 플랫폼 추가',
  'address': '주소',
  'agree': '동의함',
  'agree_to_the_agreement_v001': '계약에 대한 동의 v0.0.1',
  'agreement': '동의사항',
  'agreement_is_required': '동의가 필요합니다.',
  'airdrop_success': '🎉 지갑에 100,000 P2U 코인이 추가되었습니다.',
  'airdrop_previously_received': '🚫 이전에 100,000 P2U 코인을 받았습니다.',
  'alien_identity_verification': '외국인 본인인증',
  'amount_in': '@token 금액',
  'amount_in_krw': '원화 금액',
  'amount_in_usdt': 'USDT 화 금액',
  'amount_in_msq': 'MSQ 금액',
  'amount_not_swapped': '지갑에 MATIC 이 충분하지 않습니다',
  'amount_swapped': '스왑된 금액',
  'and_final_proceedings_11': '및 최종 승인 결정 진행',
  'announcement': '알림 사항',
  'add_document': '문서 추가',
  'add_family_document': '가족 관계 문서 추가',
  'app_language': '언어설정',
  'application_date': '신청일시',
  'apply_for_super_save': 'SUPER SAVE 신청하기',
  'super_trust_tool_tip_content':
  '슈퍼 트러스트는 충성도가 높은 사용자에게 혜택과 특전을 제공하기 위해 시작된 프로그램입니다.',
  'super_trust_tool_tip_label': '슈퍼 트러스트란 무엇인가요?',
  'woohoo': '주정산 재참여 50% 이상 달성 🥳',
  'super_trust_bottom_sheet_content':
  '귀하는 충성도가 높은 회원으로\n인정 되었으며 슈퍼 트러스트 NFT를\n드리게 되어 기쁘게 생각합니다.',
  'apply_for_super_save_helper_service': 'SUPER SAVE 도우미 서비스 신청',
  'approval_date': '참여일시',
  'approved': '승인 완료',
  'are_you_sure_you_want_to_cancel': '취소하시겠습니까 ?',
  'participation_cancel_dialog_title': '슈퍼세이브 참여 취소',
  'super_save_participation_cancel_dialog_title':
  '참가를 완료하지 못했습니다. 정말 취소하시겠습니까?',
  'complete_later': '나중에 완료',
  'as_monday_1':
  '- 외상매도 결제대금 지급방식은 선택한 외상매도의 결제대금 지급기간 동안 일일 분할지급 되며, 매주 월요일 주간 정산하여 일괄 지급됩니다.',
  'at_the_repayment_12':
  '거래완료와 동시에 매도자(본인)는 외상대금에 대한 채권(365일 분할 수금) 이 발생하며, 엠스퀘어글로벌㈜는 채무가 발생하게 됨을 이해하며, 채무 미변제에 대한 위험요소가 있음을 명확하게 인지하고 있습니다. 채무변제 진행과정에서 발생하는 문제에 대해서는 상호간 원만하게 협의함을 '
      '원칙으로 함에 동의합니다.',
  'attempts_remaining': '남은 시도 횟수',
  'available_balances': '사용 가능한 잔액',
  'available_token': '사용 가능한 @token',
  'back_to_home': '홈으로 돌아가기',
  'back_to_home_page': '홈페이지로 돌아 가기',
  'balance_certificate': '잔액증명서',
  'balance_certificate_img': '잔액증명서 img',
  'balance_check': '잔액 확인',
  'balance_sync': 'P2U 채굴',
  'balance_sync_details_subtitle': '다음 날짜에 카드 내역이 처리되었습니다.',
  'balance_sync_info': '00:00:00 AM부터 마지막 채굴 시간까지의 스캔 기간입니다.',
  'balance_sync_date': '@start_date ~ @end_date',
  'balance_sync_last_updated': '마지막: @last_updated',
  'balance_sync_details': '밸런스 동기화 세부 정보',
  'balance_sync_not_processed_yet': '아직 처리되지 않음!',
  'balance_sync_msg': '대기 중인 요청이 완료되면 알림을 받게 됩니다.',
  'company_card': '카드회사 엑세스 정보를 입력 해야합니다.',
  'bank': '은행',
  'bank_account': '은행 계좌',
  'bank_account_deleted': '은행 계좌가 삭제됨',
  'bank_account_not_added': '은행 계좌가 추가되지 않음',
  'bank_account_not_deleted': '은행 계좌가 삭제되지 않음',
  'bank_account_not_found': '계좌번호를 찾을 수 없습니다. 다시 확인 해주세요.',
  'bank_choice': '은행 선택',
  'bank_transfer_paypal_and_more': '은행 송금, 페이팔 등',
  'being_paid': '지급 중',
  'card_management': '카드 관리',
  'birth_date': '생년월일',
  'boarding_screen_tagline_1': '지원되는 매장에서 제품을 구매하고 MSQ 지갑으로 결제하세요.',
  'boarding_screen_tagline_2':
  '모든 디지털 자산을 간단하고 쉽게 처리합니다. 저장, 전송 및 거래까지 가능합니다.',
  'boarding_screen_tagline_3': 'MFA 인증 시스템을 통해 거래 및 자산 관리를 계속 제어하십시오.',
  'boarding_screen_tagline_4': '적립된 포인트는 가맹점에서 캐쉬백으로 사용 가능',
  'bug_report': '버그 보고서',
  'bug_report_msg': 'SUPER SAVE에 대한 문제나 피드백을 보내주세요.',
  'bug_report_title': 'SUPER SAVE에 문제가 있나요?',
  'buy_products': '제품 구매',
  'byungho_choi': '최병호',
  'calculation_of_amount_18': '외상매도 결제대금 산정',
  'calculation_of_amount_18_usdt':
  '외상매도 결제대금 합계(USDT 구매 @token+입금한 @token)',
  'calculation_of_amount_tooltip': '(USDT 구매 @token + 입금 @token)',
  'calculation_of_payable_21': '외상매도 결제대금 일일균등 지급금 산정',
  'camera_rotation': '카메라회전',
  'cancel': '취소',
  'cancel_ad_creating': '광고 작성을 취소하시겠습니까?',
  'cancel_participation': '취소',
  'modify': '수정',
  'cancellation': '취소',
  'cancellation_is_complete': '취소가 완료되었습니다',
  'cannot_be_canceled': '취소할 수 없다',
  'card_added': '카드 정보를 확인하는 중입니다...',
  'card_company': '카드사',
  'card_company_cannot_be_empty': '카드 회사는 비어 있을 수 없습니다.',
  'card_not_added': '카드를 추가할 수 없습니다. 다시 시도해 주세요.',
  'card_password': '카드사 웹사이트 로그인 PW',
  'case': '건',
  'category': '카테고리',
  'change_password': '거래 비밀번호 변경',
  'characters': '문자',
  'check': '확인',
  'check_balance_certificate': '잔액증명서 확인',
  'check_super_details_10': 'SUPER SAVE 지갑전송 내용 확인',
  'check_minimum_Requirements': '최소 요구 사항 확인',
  'children_under_save_2': '만 14세 미만은 SUPER SAVE를 이용하실 수 없습니다.',
  'choose_a_lookup_period': '조회 기간 선택',
  'clear_filters': '필터 지우기',
  'click_to_picture_7': '클릭하여 카메라가 작동되면 신분증을 얼굴 밑에 놓고 촬영하세요.',
  'click_to_picture_8': '푸시하여 카메라가 작동되면 신분증을 얼굴 옆에 놓고 촬영하세요.',
  'click_to_yourself_5': '클릭하여 카메라가 작동되면 직접 촬영하세요.',
  'close': '닫기',
  'coin_price': '코인 가격',
  'comment': '코멘트',
  'currency_change': '통화 변경',
  'company_registration_number': '사업자등록번호',
  'add_p2u_store_photo_invalid': '스토어 사진은 필수입니다.',
  'add_p2u_company_document_invalid': '영수증 사진은 필수입니다.',
  'add_p2u_store_name_invalid': '스토어 이름은 필수 입력 사항입니다.',
  'add_p2u_store_category_invalid': '비즈니스 업종이 필수입니다.',
  'add_p2u_store_detail_invalid': '스토어 세부 정보 필수',
  'add_p2u_store_city_invalid': '시/카운티는 필수 입력 사항입니다.',
  'enter_company_registration_number': '회사 등록 번호 입력',
  'completed': '완료',
  'confirm': '확인',
  'country_code': '국가번호',
  'phone_num': '휴대폰번호',
  'usdt_conset_title': '서비스 이용을 위해 동의가 필요합니다',
  'participation_usdt': '[필수] SUPER SAVE USDT 약관 및 동의사항',
  'registration_usdt': '[필수] 본인 확인 서비스 약관 및 동의사항',
  'confirm_change_password_1':
  'MSQUARE MARKET 지갑의 비밀번호를 변경하려면 신원을 확인하십시오.',
  'confirm_change_password_2': '로그인 후 거래에 사용하는 비밀번호를 변경할 수 있습니다.',
  'confirm_new_password': '새 암호를 확인합니다',
  'confirm_pass': '비밀번호 확인',
  'confirm_payment': '결제 확인',
  'confirm_traded_19': '- 위의 내용이 정상적으로 거래되었음을 확인합니다.',
  'confirmation_date': '확인일시',
  'connect_bank_account_complete_dialog_title': '계좌 등록이 완료되었습니다.',
  'connect_bank_account_complete_result_second':
  '영업일 기준 1일 이내로\n담당자가 등록된 정보를 확인하며\n등록 완료 시 SUPER SAVE가 가능합니다.',
  'connect_bank_account_subtitle': '지급금 입금 및 양도소득세 정산을 위해 필요합니다.',
  'connect_bank_account_title': '계좌를 등록해주세요.',
  'connected_platforms': '플랫폼 관리',
  'consent_to_use_of_service': '서비스 이용 동의',
  'consent_to_use_of_service_v001': '서비스 이용 동의 v0.0.1',
  'contact_us': '문의하기',
  'contact_us_error_1': '연락해 주셔서 감사합니다',
  'contact_us_error_2': '귀하의 응답을 받을 수 없습니다. 다시 시도해주세요',
  'contact_us_error_3': '제목 값이 비어 있습니다.',
  'contact_us_error_4': '이메일 값이 비어 있습니다.',
  'contact_us_error_5': '메시지 값이 비어 있습니다.',
  'contact_us_error_6': '이메일이 잘못되었습니다! 다시 시도해주세요',
  'contact_us_msg': '질문 및 문제가 있는 경우 당사에 문의하십시오.',
  'contact_us_title': '어떻게 도와 드릴까요?',
  'copy': '복사',
  'copy_address': '주소 복사',
  'copy_and_send_referral_code':
  '추천 코드를 복사하여 친구에게 보내면 추가 혜택을 받을 수 있습니다. 친구에게 복사하거나 공유하려면 탭하세요.',
  'create': '생성하다',
  'create_id': '유저 아이디 생성',
  'create_p2p_ad': 'P2P 목록 생성',
  'create_pass': '지갑 비밀번호 생성',
  'create_pass_agreement_label_1':
  'MSQUARE MARKET은 블록체인 기술을 기반으로 한 탈중앙화 지갑으로 사용자의 비밀번호를 저장하지 않습니다.',
  'create_pass_agreement_label_2':
  '비밀번호 관리의 책임은 이용자에게 있으며, 비밀번호 분실 시 복구가 불가능하며, MSQUARE MARKET 지갑의 모든 디지털 자산에 대한 접근이 불가능합니다.',
  'create_pass_agreement_label_3':
  '참고: MSQUARE는 비밀번호 분실 시 도움을 드릴 수 없습니다. 잠시 시간을 내어 메모장에 비밀번호를 저장해 두십시오.',
  'create_pass_agreement_title': '비밀번호 분실에 대한 책임은 이용자에게 있음',
  'credit_payment_rate': '외상대금 지급율',
  'credit_sale_amount_4':
  '외상매도 신청 \n@deposit_token @standardcurrency 환산금액',
  'credit_sale_amount_pm': '외상 매도 요청 \n@token @pm 전환 금액',
  'credit_sale': '외상매도권',
  'credit_sale_application': '외상매도권 사용자',
  'credit_sale_application_modify': '외상매도권 사용자 (수정하다)',
  'super_save_application': '슈퍼세이브 신청자',
  'super_save_application_modify': '슈퍼세이브 신청자 (수정하다)',
  'super_save_shared_mesage':
  '내 슈퍼 세이브 추천 코드는 다음과 같습니다: @code 스퀘어 마켓 다운로드: https://onelink.to/mq2g22',
  'super_save_shared_mesage_fb':
  '내 슈퍼 세이브 추천 코드는 다음과 같습니다: @code 플레이스토어/앱스토어에서 MSQUARE MARKET 다운로드하기',
  'c_r_modify_msg': '외상매도 금액만 변경할 수 있습니다.',
  'c_r_modify_done': '수정 요청이 전송되었습니다.',
  'c_r_modify_done_title': '수정 요청이 접수되었습니다.',
  'credit_sale_daily_equal_payment': '외상매도 일일균등 \n지급금',
  'credit_sale_msq_pairs_quantity': '외상매도 신청 @token Pairs 수량',
  'credit_sale_total_msq_quantity': '외상매도 총 @token 수량',
  'credit_sale_quantity_11': '외상매도 신청 @token 수량',
  'credit_sale_quantity_10': '외상매도 신청 @token 수량',
  'total_credit_sale_amount': '총 외상매도 신청 @token 수량',
  'cash_buy_total_amount': '회사 입금 구매한 SUT + 직접 전송한 SUT 합계 수량',
  'total_credit_sale_amount_cr_s': '(!) 안내사항',
  'cash_buy_total_amount_cr_s': '회사에 현금 입금 후, 직접 구매한 SUT',
  'credit_sale_rate_12': '외상매도 결제대금 지급기간(지급률)',
  'credit_sale_rate_7': '외상매도 결제대금 \n지급기간(지급률)',
  'credit_sales_method_9': '외상매도 결제대금 \n지급방식',
  'credit_sales_payment': '외상매도 결제대금',
  'credit_sales_payment_amount': '외상매도 결제금액',
  'credit_sales_payment_method': '외상매도 결제대금 지급방식',
  'credit_sell_request_msq_quantity': '외상매도 신청 \n@token 수량',
  'credit_transaction_credit_6':
  '외상거래는 거래에서 매매계약이 성립되어 상품이 인도 되었지만, 그에 대한 대금은 일정기간이 지난 후에 결제되는 거래를 말하며, 외상매매 또는 신용거래라고 하기도 합니다. 이러한 신용거래는 신용을 기반으로 장래 채무를 지급하는 대차관계가 발생합니다.',
  'criteria_during_participation': '참여중 기준',
  'cumulative_payment': '누적지급금',
  'current_password': '현재 비밀번호',
  'current_price_1msq': '현재가 1@token=@standardamount@mode',
  'otc_current_price_1msq': 'OTC 현재가 1 @token=@standardamount@mode',
  'open_market_price_1msq':
  'Open Market 현재가 1 @token=@marketamount@mode',
  'currently_unavailable': '현재 이용이 불가합니다',
  'currency_selection': '통화 선택',
  'daily_equal_payment': '일일균등지급',
  'daily_payment': '일일지급금',
  'daily_payment_1': '일일결제대금',
  'daily_payout': '일일지급금',
  'date_and_time_of_foreign_sale': '외상매도 일시',
  'date_and_time_of_payment': '외상대금 수금 만료일시',
  'date_of_birth': '생년월일',
  'date_of_transaction': '거래일시',
  'day': '일',
  'deadline': '마감일시',
  'decline_approval': '회사 승인 거절',
  'delete_account': '계좌 삭제',
  'delete_store': '매장을 삭제하시겠습니까?',
  'delete_store_msg': '정보 수정을 위해 삭제하지 마세요!',
  'delete_card': '카드 삭제를 정말 원하시나요?',
  'delete_platform': '플랫폼 삭제를 정말 원하시나요?',
  'denied': '거부됨',
  'deposit': '입금',
  'deposit_account': '입금 계좌',
  'device_default': '장치 기본값',
  'deposit_complete': '입금완료',
  'deposit_scheduled': '입금예정',
  'deposit_scheduled_1': '입금예정 ',
  'details_of_my_participation_amount': '나의 참여금액 상세',
  'discounted_products': '할인 제품',
  'done': '완료',
  'email_address': '이메일 주소',
  'enter_account_number': '계좌번호 입력',
  'enter_amount': '금액 입력',
  'enter_card_password': '로그인 패스워드를 입력하세요',
  'enter_login_id': '로그인 아이디를 입력하세요',
  'enter_message': '메시지 입력',
  'enter_numbers_only': '숫자만 입력',
  'enter_pass': 'MSQUARE MARKET 비밀번호 입력',
  'enter_the_transmitted_txid_value': '전송된 TXID값 입력',
  'enter_user_id': '유저 아이디를 입력하십시오.',
  'error': '오류',
  'error_404': '페이지를 찾을 수 없습니다.',
  'error_500': '내부 서버 오류',
  'error_500_msg': '트래픽이 현재 매우 높습니다.',
  'error_502': '잘못된 게이트웨이',
  'exit_app': '앱 종료',
  'exit_app_msg': '응용 프로그램을 종료하시겠습니까?',
  'expected_payment_amount': '지급예정 금액',
  'expiry_': '만료:',
  'education_notice': '안내사항',
  'education_add_photo': '사진 추가',
  'education_credit_Sales': '교육 이수가 필요합니다.',
  'education_done': '월 교육 이수 완료!',
  'education_tooltip_message': '교육 이수가 필요합니다. 인증\n없이는 외매권 행사가 불가합니\n다.',
  'education_issued_date': '발생날짜',
  'education_current_period': '이번회차',
  'month_schedule': '월 교육 일정',
  'education_next_period': '다음차 교육이수기간',
  'education_verify': '인증 하기',
  'education_waiting_approval': '심사중',
  'education_reattach': '다시 첨부하기',
  'education_completed': '이수 완료',
  'education_denied': '거절됨, 다시시도',
  'education_document': '여기에 사진을 추가하세요.',
  'add_education_document': '교육 사진 추가',
  'super_save': 'SUPER SAVE',
  'file_upload': '파일 업로드',
  'upload': '업로드',
  'file_uploaded': '파일 업로드 성공',
  'file_size_warning': '파일 크기가 10MB 이상',
  'file_upload_waiting': '파일 업로드 중, 잠시만 기다려주세요...',
  'fingerprint_authentication': '지문 인증',
  'fingerprint_failed': '지문 인증 실패',
  'fingerprint_popup': '지문 인증을 활성화하려면 비밀번호를 입력하세요.',
  'fingerprint_text': '비밀번호 대신 지문을 사용하여 결제를 처리하세요.',
  'first_must_be_lower': '첫 번째 문자는 소문자여야 합니다',
  'family_relationship_document': '가족관계증명서 및 확약서',
  'for_msq_service_15':
  'MSQ 외상거래를 위하여는 MSQ를 이용 P2P거래 및 외상거래신청을 해야하는 바, 본인이 방법에 미숙함으로 인하여 발생하는 기망, 사기, 도난 등 사고방지를 위해서 모든 절차를 "도우미 서비스"에 일임하고자 합니다. 도우미 서비스 이용으로 인한 어떠한 법적책임도 회사에 묻지 '
      '않을 것에 동의합니다.',
  'for_transfer_28': '- 정산 후 이체는 이체 건당 수수료가 부과됩니다.',
  'foreigner_registration_number': '외국인등록번호',
  'foreigners_residing_korea_5': '국내거주 또는 방문 외국인',
  'from': '~에서',
  'no_transaction_of_p2u_mining': '채굴할 P2U 트랜잭션이 없습니다.',
  'get_involved': '이어서 진행하기',
  'go_to_super_save': 'SUPER SAVE 바로가기',
  'go_to_credit_sale': '외상매도권 바로가기',
  'great': '확인',
  'having_problems_with_super_save': 'SUPER SAVE에 문제가 있나요?',
  'hello': '안녕하세요.',
  'history': '히스토리',
  'history_list_empty': '기록 목록이 비어 있습니다!',
  'home': '홈',
  'hong_gil_dong': '홍길동',
  'hundred_million': '억',
  'i_agree_content_24': '본인은 신청한 내용으로 MSQ 외상매도에 동의합니다.',
  'i_clearly_transaction_11': '본인은 슈퍼세이브가 MSQ외상거래임을 명확히 이해하고 있습니다.',
  'i_sure': '확인.',
  'id_verification_verification_3': '본인확인을 위해 신분증 인증이 필요합니다.',
  'idpassport__face_photo': '신분증/여권+얼굴사진',
  'idpassport_photo': '신분증/여권 사진',
  'if_234_21':
  '- 본 확인증을 임의로 위·변조하여 행사할 경우 형법(제251조 및 234조)에 따라 처벌받을 수 있습니다.',
  'if_change_23': '- 월요일이 휴일인 경우, 익영업일에 금액 변동없이\n지급됩니다.',
  'if_charged_43': '- 2개 이상 SUPER SAVE에 참여하실 경우 1개만 수수료가 부과됩니다.',
  'if_you_choose_to_cancel': '취소를 선택하면 입력한 세부 정보가 손실됩니다.',
  'if_you_photographed_2': '신분증을 영역안에 맞추면 \n 자동으로 촬영됩니다.',
  'if_you_quotes_10':
  '슈퍼세이브 참여 신청을 위해 MSQ를 입금하였으나, 단순 변심으로 인하여 환송신청을 할 경우, 특금법 신고 수리된 거래소 가격을 참고하여 10일 이내 MSQ로 환불한다.\n(예시) 환송 MSQ = 최초신청금액 / 거래소 MSQ 시세',
  'image_successfully_saved_in_gallery': '이미지가 갤러리에 성공적으로 저장되었습니다.',
  'image_upload': '이미지 업로드',
  'id_photo_upload': '신분증 사진 업로드',
  'percent': '비율',
  'profile_photo_upload': '프로필 사진 업로드',
  'photo_uploaded': '사진이 업로드되었습니다.',
  'document_uploaded': '문서가 업로드되었습니다.',
  'stores': 'P2U 무료 채굴 상점 찾기',
  'p2u_store': 'P2U 무료 채굴 상점',
  'my_p2u_store': '내 P2U 무료 채굴 상점@s@n@m@e',
  'p2u_store_business_number_txt1': '입력 숫자가 부족합니다.',
  'registered_p2u_store': '등록한 P2U스토어(@stores개)',
  'p2u_store_near': '가까운 P2U 무료 채굴 상점',
  'p2u_store_payment_error': '결제를 처리하는 동안 오류가 발생한 것 같습니다. 다시 시도해 주세요.',
  'p2u_find_in_this_area': '이 영역에서 찾기',
  'p2u_quantity': 'P2U 수량',
  'p2u_krw_conversion_amount': 'P2U 원화 전환 금액',
  'filters': '필터',
  'add_p2u_store': 'P2U 무료 채굴 상점 추가',
  'add_p2u_page_title': 'P2U 무료 채굴 상점 등록',
  'add_p2u_page_title_update': 'P2U 스토어 업데이트',
  'update_p2u_popup_title': 'P2U 가맹점 등록 중복확인',
  'update_p2u_popup_subtitle': 'P2U 가맹점에 이미 존재하는\n사업자등록번호입니다.',
  'p2u_store_verfied': '등록 가능한 사업자등록번호입니다.',
  'add_p2u_first_description': 'P2U 무료 채굴 상점 세부 정보를 입력하세요.',
  'add_p2u_second_description': '추가한 가맹점은 모든 사용자에게 표시됩니다.',
  'add_p2u_guide': 'P2U 무료 채굴 상점 등록 가이드',
  'add_p2u_store_photo_title': 'P2U 무료 채굴 상점 홍보사진 추가',
  'add_p2u_store_photo': '홍보 사진 첨부하기',
  'add_p2u_store_photo_uploaded': '스토어 사진 업로드',
  'add_p2u_store_document_upload': '스토어 문서 업로드',
  'add_p2u_company_document_title': 'P2U 무료 채굴 상점 카드영수증 추가',
  'add_p2u_company_document': '카드 영수증 첨부하기',
  'add_p2u_store_name_title': 'P2U 무료 채굴 상점 이름',
  'add_p2u_store_name': 'P2U 무료 채굴 상점 업종',
  'add_p2u_merchant_code_title': '상인 코드',
  'add_p2u_merchant_code': '상인 코드를 입력하세요',
  'add_p2u_store_category_title': '등록할 가맹점 업종',
  'add_p2u_store_category': '업종선택',
  'add_p2u_store_detail_title': '등록할 가맹점 상세 정보',
  'add_p2u_store_detail': '가맹점 상세 정보를 입력하세요.',
  'add_p2u_store_select_city': '가맹점 도시를 선택하세요.',
  'add_p2u_store_city': '등록할 가맹점이 있는 도시',
  'map_link': '등록할 가맹점 네이버 검색 링크',
  'optional': '선택 과목',
  'store_web_link': '네이버 검색링크 입력',
  'invalid_map_link': '등록할 가맹점 네이버 검색 링크(https://를 꼭 포함해주세요.)',
  'no_store_detail': '세부정보가 없습니다.',
  'add_p2u_store_address_title_p1': '등록할 가맹점 주소를 입력후\n하단의',
  'add_p2u_blue_address': ' 파란색 주소',
  'add_p2u_store_address_title_p2': '를 선택하세요',
  'add_p2u_store_address': '주소 입력후 반드시 파란색 주소 선택',
  'add_p2u_store_address_invalid_message': '주소 드롭다운에서 주소를 선택하세요.',
  'add_p2u_store_added_successfully': 'P2U 스토어가 성공적으로 추가되었습니다.',
  'add_p2u_store_store_added': '이전에 P2U 스토어를 이미 추가하셨습니다.',
  'add_p2u_store_submit': '가맹점 등록하기',
  'filter_p2u_store_distance_input_label': '지도 거리',
  'filter_p2u_store_distance_input_label2': 'KM 반경',
  'add_p2u_store_submit_update': '스토어 업데이트',
  'total_store': '스토어',
  'all_store': '모든 P2U 무료 채굴 상점',
  'all_store_in_location': '@x KM P2U 무료 채굴 상점',
  'all_store_in_city': '@city 의 모든 P2U 무료 채굴 상점',
  'in': '안에',
  'in_progress': '진행 중',
  'incorrect_password': '잘못된 비밀번호',
  'index__1_month': '@index월',
  'information_on_participation_11': '참여가능한도 안내',
  'input_cannot_be_empty': '입력은 비워 둘 수 없습니다.',
  'internet_restored': '인터넷 복원',
  'invalid_password': '유효하지 않은 비밀번호',
  'invalid_token_type': '잘못된 토큰 유형',
  'invoices_to_this_mail': '인보이스는 이 이메일로 발송됩니다.',
  'it_means_deadline_8':
  '유저는 외상거래 결제대금에 대한 채권이, MSQUARE 본사는 채무가 발생하게 되며, 약정한 지급기한내에 대금 결제를 마무리하는 것에 서로 동의함을 뜻합니다.',
  'koreans_aged_14_and_over': '만 14세 이상 내국인',
  'krw': 'KRW',
  'last': '마지막',
  'last_7_digits': '뒤 7자리',
  'learn_more': '더 알아보기',
  'let_go': '보내다',
  'listing_type': '리스팅 유형',
  'login_id': '카드사 웹사이트 로그인 ID',
  'logout': '로그아웃',
  'logout_msg': '로그아웃 성공.',
  'm_square_global_co_ltd': '주식회사 슈퍼트러스트',
  'm_square_market': 'MSQUARE MARKET',
  'main_account': '주계좌',
  'main_account_cannot_deleted': '기본 계정은 삭제할 수 없습니다. 해결방법: 변경할 계정을 추가후 메인 계정변경 그리고 현 계정을 삭제. ',
  'main_bank_account_changed': '주 은행 계좌가 변경됨',
  'main_bank_account_not_changed': '기본 은행 계좌가 변경되지 않음',
  'match_your_photographed_3': '얼굴과 신분증을 영역안에 맞추면\n자동으로 촬영됩니다.',
  'make_a_payment': '결제하기',
  'max': '최대',
  'message': '메시지',
  'msq_market_selling_11': 'MSQ 외상매도 전 시가총액',
  'msq_price_sale_17': '외상매도 시점 @token 시세',
  'msq_transmission_date': '@token (전송일시 @date)',
  'msq_wallet_address': '@curr 지갑주소 ',
  'must_include_special': '특수 문자와 숫자를 포함해야 함',
  'must_include_upper_lower': '대문자와 소문자를 포함해야 함',
  'mutual_confidentiality_problem_13':
  '본 MSQ 외상거래 사실(세부내용 포함)에 대하여 상호 비밀유지를 원칙으로 하며, 사전동의 없이 타인이나 타회사에 알리는 행위, 인터넷 커뮤니티, 게시판, SNS 등 불특정다수에게 알리는 행위 등 비밀유지위반으로 발생되는 문제에 대하여 민형사상 '
      '무한법적책임이 위반당사자에게 있음에 동의합니다.',
  'mute_push_notifications': '푸시 알림 뮤트하기',
  'mute_notifications': '알림 음소거',
  'my_account': '내 계좌',
  'my_bank_accounts_note1.': '주계좌로 등록된 계좌에서 거래가 체결됩니다.',
  'my_contribution': '나의 참여금액',
  'my_daily_equal_payout': '나의 일일균등지급금',
  'my_points': '나의 보유 P2U',
  'my_remaining_balance': '나의 잔여 외상대금',
  'my_wallet': '내 지갑',
  'mobile_phn_verification': '휴대폰 인증',
  'n_week_of_month': '월 @w주차',
  'name': '이름',
  'name_1': '이름',
  'name_of_bank': '은행명',
  'no_companies': '회사 없음',
  'no_bank_account': '슈퍼 세이브에 참여하려면 은행 계좌를 추가해야 합니다',
  'no_usdt_wallet': '슈퍼 세이브 참여를 완료하려면 지갑을 추가해야 합니다',
  'national_identity_verification': '내국인 본인인증',
  'nationality': '국적',
  'nationality_selection': '국적 선택',
  'nearest': '가장 가까운',
  'new_notification': '새 알림',
  'new_member_only_can_add_referral': '추천인 추가는 신규가입만 가능.',
  'new_password': '새 비밀번호',
  'newest': '최신',
  'news': '소식',
  'next': '다음',
  'no_card': '⚠️ 사진에서 감지된 카드가 없습니다. 이 이미지를 계속 사용하시겠습니까?',
  'no_card_added': '카드 추가 안 함',
  'no': '아니요',
  'no_file_selected': '선택한 파일 없음',
  'no_internet_connection': '인터넷에 연결되지 않음',
  'no_news': '뉴스 없음',
  'no_permission': '권한 없음',
  'no_permission_permanent': '권한이 영구적으로 거부되었습니다. 설정으로 이동하여 허용하세요.',
  'no_platform_added': '플랫폼 추가되지 않음',
  'no_record_found': '기록을 찾을 수 없습니다.',
  'no_registered_accounts': '등록된 계좌가 없습니다.',
  'no_result': '조회 결과가 없습니다.',
  'no_tokens': '토큰이 없습니다.',
  'not_enough_balance': '잔액이 부족합니다.',
  'not_enough_msq': 'MSQ가 충분하지 않음',
  'not_enough_msqp': 'MSQP가 충분하지 않음',
  'not_enough_p2up': 'P2UP가 충분하지 않음',
  'not_enough_tokens': '@token 가 충분하지 않음',
  'nothing_to_show': '표시할 항목 없음',
  'notification_supersave_payout_approved':
  'SUPER SAVE 정산 요청이 승인되었습니다.',
  'notification_supersave_title_approved': 'SUPER SAVE 참여 요청이 승인되었습니다.',
  'notification_supersave_title_declined': 'SUPER SAVE 참여 요청이 거부되었습니다.',
  'notifications': '안내',
  'notifications_for_settings': '알림 설정',
  'notification_credit_success':
  '새로운 외상매도권을 받았습니다. 참여를 완료하는 것을 잊지 마세요.',
  'notifications_sound': '알림 소리',
  'notification_setting': '알림 설정',
  'notification_super_save': '슈퍼 세이브',
  'notification_device_default': '장치 기본값',
  'notification_credit_failed': '외상 매도 거래가 실패했습니다.',
  'notifications_from': '에서',
  'notifications_to': '에게',
  'np_cp_not_match': '새 비밀번호와 비밀번호 확인이 일치하지 않습니다.',
  'same_cp_np': '새 비밀번호는 현재 비밀번호와 같을 수 없습니다.',
  'null_value': '값은 비워둘 수 없습니다.',
  'number_of_people': '명',
  'ok': '확인',
  'okay': '좋아요',
  'btn_check': '확인',
  'we_r_sorry': '죄송합니다!',
  'req_not_fulfil': '이 슈퍼트러스트 NFT의 최소 요구 사항을 충족하지 않습니다!',
  'nft_available': 'NFT 혜택 제공',
  'nft_not_available': 'NFT 혜택 이용 불가',
  'nft_benefits_lost': 'NFT 혜택 손실',
  'nft_requirements': 'NFT 요구 사항',
  'nft_requirements_txt1': '최소 요구 사항',
  'nft_requirements_txt2': '슈퍼 트러스트 혜택을 받기 위해 충족해야 하는 최소 요건은 다음과 같습니다.',
  'nft_requirements_txt3':
  '슈퍼 세이브 주간 정산 금액의 50% 이상을 재참여 멤버십으로 적립해야 합니다.',
  'nft_paused': '슈퍼트러스트 NFT 권한이 더이상 없습니다.',
  'nft_paused_det':
  '최소 요구 사항을 충족하지 못해 슈퍼트러스트 NFT 혜택을 잃었습니다. 혜택을 받기위해선 슈퍼트러스트 NFT를 확보 해야합니다.',
  'one_two_bank_11011234': '하나둘은행 1101******1234',
  'or': '또는',
  'on': '켜기',
  'off': '꺼짐',
  'order_cannot_be_deleted': '주문을 삭제할 수 없음',
  'order_completed': '주문완료',
  'order_not_placed': '귀하의 주문을 할 수 없습니다. 다시 시도해 주세요',
  'order_successfully_deleted': '주문이 성공적으로 삭제됬습니다.',
  'our_products': 'MSQUARE 플랫폼 소개 / SNS',
  'other': '다른',
  'out': '밖으로',
  'p2p_listings': '내 P2P 목록',
  'p2p_listings_empty': 'P2P 목록이 비어있습니다',
  'p2p_trade': 'P2P 거래',
  'p2p_trading': 'P2P 거래',
  'p2p_trading_msg': '디지털 자산 거래',
  'paid_out': '지급 완료',
  'paid_with': '결제 수단',
  'participant_num': '참여 현황 총 @n 건',
  'participate_in_super_save': 'SUPER SAVE 참여',
  'participation_complete': '승인대기 / 승인완료 목록보기',
  'applied_lists': '참여리스트',
  'applied_list_empty': '조회 결과가 없습니다!',
  'pass': '비밀번호',
  'pass_change_fail': '비밀번호가 변경되지 않음',
  'pass_change_success': '비밀번호가 성공적으로 변경됨',
  'pass_limit_reached': '비밀번호 시도 횟수 한도에 도달했습니다. 5분 후에 다시 시도해주세요.',
  'pass_not_match': '비밀번호가 일치하지 않습니다',
  'pass_verify': '비밀번호 유효성 검사',
  'payment_amount': '지급금액',
  'payment_completed_amount': '지급완료 금액',
  'payment_details': '지급내역',
  'get_card_management': '카드 정보수집',
  'payment_mondays_11':
  '- 결제대금 지급기간 동안 일일 분할지급 되며, 매주 월요일 주간 정산하며 지급됩니다.',
  'payment_status_by_case': '참여 건별 지급 현황 총 @n 건',
  'permissible_to_sale_2': '외상매도 신청가능한도',
  'phone_number': '휴대폰번호',
  'place_your_card_5':
  '신분증을 얼굴 좌측이나 우측\n에 두고 영역에 맞춰 촬영하세요.\n신분증에 빛이 반사되지 않도록\n주의해주세요.',
  'platform': '플랫폼',
  'please_add_family_relationship_document': '여기에 가족 관계 서류를 추가하세요.',
  'please_check_complete_3': '신청 완료 시 수정이 불가능하니 꼼꼼히 확인해주세요.',
  'please_check_information_2': '신청 정보를 확인해주세요.',
  'please_enter_application_2': '외상매도 신청에 필요한 정보를 입력해주세요.',
  'please_enter_information_2': '신청인 정보를 입력해 주세요.',
  'please_enter_number_2': '주민등록번호를 입력해주세요.',
  'please_enter_phone': '휴대폰번호를 입력해주세요.',
  'please_enter_payment_information': '결제대금 정보를 입력해주세요.',
  'please_enter_valid_amount': '유효한 금액을 입력하세요',
  'please_enter_6_digit': '인증번호 6자리를 입력해주세요.',
  'please_note': '알려드립니다.',
  'please_note_approval_5':
  '슈퍼세이브 신청 후, 본사 사정에 의하여 승인 거절 될 수 있는 점, 유의하시기 바랍니다. 슈퍼세이브 신청(MSQ외상 거래 신청)은 슈퍼세이브 승인(MSQ 외상거래 승인)을 보장하지 않습니다.',
  'please_prepare_your_id': '신분증을 준비해주세요.',
  'please_read_agree_2': '아래의 내용을 읽고 "동의함"을 입력해주세요.',
  'please_read_agree_22': '아래의 내용을 읽고 "동의함"을 입력해주세요.',
  'please_register_clear_3': '신분증의 글자가 선명한지 \n 확인하신 후 등록해주세요.',
  'please_register_clear_4': '얼굴과 신분증의 글자가 선명한지\n 확인하신 후 등록해주세요.',
  'please_send_sale_3': '외상매도를 신청한 MSQ를 \n보내주세요.',
  'please_send_save_3': 'SUPER SAVE에 대한 문제나 피드백을 보내주세요.',
  'please_set_id_4': '신분증에 빛이 반사되지 않도록 \n 영역안에 맞춰주세요.',
  'pls_create_pass': '거래를 위한 비밀번호를 만드세요.',
  'possibility_to_participate': '참여가능한도',
  'possible_to_participate': '참여가능',
  'price_integration': '시세 연동',
  'privacy_policy': '개인 정보 정책',
  'privacy_settings': '개인 정보 설정',
  'open_setting': '설정 열기',
  'proceed_transaction': '이 트랜잭션을 계속하시겠습니까?',
  'proceed_wallet_termination': '계정 삭제 진행을 위해 아래 비밀번호 입력',
  'really_sure': '거래를 계속 진행하시겠습니까?',
  'recipient': '받는사람',
  'recommended': '권장됨',
  'refresh': '새로고침',
  'refresh_balance': '잔액 새로 고침',
  'refuse': '거절하다',
  'reserved_cash': '(준비된 현금)',
  'register_bank_account': '은행 계좌 등록',
  'change_bank_account': '은행 계좌 변경',
  'change_bank_account_req': '은행 계좌 변경 요청.',
  'has_pending_req': '이미 보류 중인 변경 요청이 있습니다.',
  'registration': '등록하기',
  'registration_date': '등록일시',
  'registration_number_digits_7': '등록 번호는 7자리여야 합니다.',
  'representative_name': '대표자명',
  'request_confirmation': '등록이 완료되었습니다',
  'request_confirmation_msg': '지갑 주소가 생성되었습니다.',
  'request_for_address_and_balance': '주소 및 잔액을 요청했습니다',
  'request_for_krw_10': '외상매도 신청 @token @standardcurrency 환산금액',
  'request_for_krw_3': '외상매도 요청 @token @mode 환산금액',
  'transfer_krw': '매수대금\t을 보내세요.',
  'transfer_token': '를 보내세요.',
  'transfer_credit_sale_right_title': '외상매도권 양도',
  'transfer_credit_sale_right_txt1': '님에게',
  'transfer_credit_sale_right_txt2': ' 외상매도권을 전송하는 것에 동의 하십니까?',
  'settlement_amount': '외상매도대금\t승인 받습니다.',
  'request_for_krw_ss': '외상매도 승인 요청 금액',
  'request_for_krw_cs': '외상매도권(외매권) 사용',
  'won_cs': '원권',
  'referral': '외매권',
  'referral_code_social': '추천 코드',
  'requested_by': '에 의해 요청',
  'requested_help': '요청된 도움말',
  'requested_msq_minutes_7': '요청하신 SUT 수량을 10분이내',
  'reserve_reserve_consumption_rate': '지급준비금 소진율',
  'reserves': '지급준비금',
  'reset': '리셋',
  'resident_registration_number': '주민등록번호',
  'resolve_errors': '오류를 수정하십시오',
  'retry': '재시도',
  'Register_a_supersave_transaction': 'SUPER SAVE 거래 등록',
  'save_transaction_confirmation': '거래확인증 저장',
  'scan_finger': '계속하려면 손가락을 스캔하세요.',
  'scan_finger_to_connect': '지문을 스캔하여 거래를 확인하세요.',
  'scan_qr_code': 'QR 코드 스캔',
  'secure_layer': '보안 계층',
  'see_details': '자세히 보기',
  'see_more': '자세히 보기',
  'see_exam': '예시',
  'review': '첨부이미지 확인',
  'add_cash_transfer': '현금이체 캡쳐본 첨부',
  'add_coin_transfer': '코인전송화면 캡쳐본 첨부',
  'add_more': '+ 추가하기',
  'cash_trans_sample': '현금 이체 샘플',
  'coin_trans_sample': '코인 전송 샘플',
  'recommend_to': '나의 소개자 지정하기(외매권 주기)',
  'recommend_to_be': '내가 소개한 사람',
  'apply_ss': '슈퍼세이브 신청자(신규/재참여)',
  'apply_credit_sale': '외상매도권 사용자(외매권자)',
  'super_save_user': '슈퍼세이브 사용자',
  'credit_sale_user': '외상매도권 사용자',
  'application_type': '신청유형',
  'review_attachment': '첨부이미지 확인',
  'txid_error': '이미 등록된 TXID 입니다.',
  'select_an_accounts_13': '외상매도 결제대금 계좌 선택',
  'err_trans_cap': '전송 스크린샷을 모두 첨부해 주세요.',
  'err_txid': 'TXID를 확인하세요.',
  'tx_id_fine': '정상적인 TXID 입니다.',
  'unable_to_upload': '스크린샷을 업로드할 수 없습니다.',
  'select_bank': '은행 선택',
  'select_identity_verification_type': '본인인증 유형 선택',
  'select_your_card': '회사없음',
  'send': '전송.',
  'sender': '보낸사람',
  'sensitive_information_act_3': '민감정보는 개인정보보호법에 따라 암호화하여 안전하게 보호됩니다.',
  'sent_date': '(전송일시 @date)',
  'sent_successfully': '성공적으로 전송됨.',
  'service_withdrawal': '서비스 탈퇴',
  'service_withdrawal_apply': '탈퇴 신청',
  'service_withdrawal_complete_dialog_title': '탈퇴 신청이 완료 되어\n로그아웃 됩니다.',
  'service_withdrawal_deposit_into_account': '남은 잔액은 등록된 계좌로 입금됩니다.',
  'service_withdrawal_input_hint': '사유 입력',
  'service_withdrawal_irreversible': '탈퇴 신청은 철회되지 않으니 신중히 결정해주세요.',
  'service_withdrawal_reason_1': '앱을 사용하지 않음',
  'service_withdrawal_reason_2': '오류로 사용이 불편함',
  'service_withdrawal_reason_3': '사용법이 어려움',
  'service_withdrawal_reason_4': '직접 입력',
  'service_withdrawal_reason_title': '탈퇴 사유를 입력해주세요.',
  'service_withdrawal_rules_1': '서비스를 탈퇴하시면 모든 개인정보가 파기 됩니다.',
  'service_withdrawal_rules_2':
  '기타 의무 보관 정보는 관련 법령에 따라 별도 보관하고, 일정 기간 보유한 되 파기됩니다.',
  'service_withdrawal_rules_3': '재가입 시 회원정보, 계좌정보 등은 자동으로 복구되지 않습니다.',
  'service_withdrawal_rules_4a': '탈퇴 신청 시 영업일 기준 24시간 이내 처리 되며,',
  'service_withdrawal_rules_4b': '탈퇴 후 6개월 이내 재가입이 불가능합니다.',
  'service_withdrawal_rules_5a': '회원 탈퇴 신청 시 로그아웃',
  'service_withdrawal_rules_5b': '처리 되며,',
  'service_withdrawal_rules_5c': '로그인 및 모든 서비스 이용이 불가능',
  'service_withdrawal_rules_5d': '합니다.',
  'service_withdrawal_rules_title': '탈퇴 전 꼭 확인해주세요.',
  'set_as_main_account': '주계좌로 설정',
  'settings': '설정',
  'sound': '사운드',
  'super_save_approval_rejection': '슈퍼 저장 승인/거부',
  'super_save_daily_payouts': '슈퍼 세이브 일일 지급금',
  'p2u_auto_mining_results': 'P2U 자동 마이닝 결과',
  'date': '날짜',
  'date_': '날짜:',
  'settlement_date': '정산일',
  'settlement_date_1': '(정산일)',
  'shall_we_on_2': '지금부터 SUPER SAVE에 참여해볼까요?',
  'shall_we_sale_20':
  '지금부터 SUPER SAVE에 참여해볼까요?\n외상매도 신청 후 10분 이내에\n참여 가능합니다.',
  'shooting_number': '촬영 @number',
  'six_digit': '6자리 숫자',
  'sign_in_with': '로 로그인하다',
  'sign_in_with_apple': '애플 계정으로 로그인',
  'sign_in_with_facebook': '페이스북으로 서명',
  'sign_in_with_google': '구글 계정으로 로그인',
  'sort_by': '정렬 기준',
  'subject': '제목',
  'success': '성공',
  'sorry': '죄송합니다',
  'successful': '성공적인',
  'super_save_act_9':
  '슈퍼세이브는 자본시장법 또는 금융소비자보호법 등에 의해 보호받을 수 있는 금융상품이 아닙니다.',
  'super_save_charge_1': '담당자 확인 후 SUPER SAVE 이용이 가능합니다.',
  'super_save_charge_13': '담당자 확인 후 SUPER SAVE 이용이 가능합니다.',
  'super_save_corpo_reg_title': 'SUPER SAVE 법인 거래 등록',
  'super_save_corpo_business_license_header': '단체등록',
  'super_save_corpo_business_license_subtitle': '단체번호와 증명서를 등록해 주세요',
  'ss_corp_acc_change': '은행 계좌를 변경하려면 은행 계좌 정보를 입력하세요.',
  'super_save_corpo_name': '단체명',
  'super_save_corpo_name_hint': '회사명 입력',
  'super_save_corpo_business_license_number': '단체번호',
  'super_save_corpo_business_license_number_hint': '숫자만 입력',
  'super_save_corpo_business_license_cert': '증명서',
  'super_save_corpo_business_license_cert_hint': '파일 선택',
  'super_save_corpo_account_header': '계좌를 등록해주세요.',
  'super_save_corpo_account_header_subtitle':
  '지급금 입금 및 양도소득세 정산을 위해 필요합니다.',
  'super_save_corpo_account': '은행 선택',
  'super_save_corpo_account_number': '계좌번호 입력',
  'super_save_corpo_account_number_hint': '숫자만 입력',
  'super_save_corpo_account_bank_book': '통장사본',
  'super_save_corpo_account_bank_hint': '파일 선택',
  'super_save_day_12': 'SUPER SAVE가 마감되었습니다. 매일 10시부터 16시까지 신청 가능합니다.',
  'super_save_ended':
  'SUPER SAVE가 마감되었습니다. 매일 @start 시부터 @end 시까지 신청 가능합니다.',
  'super_save_information_1': 'SUPER SAVE 거래 등록 안내',
  'super_save_is_a_credit_transaction': '슈퍼세이브는 외상거래입니다.',
  'super_save_iscomplete_18': 'SUPER SAVE 참여가\n완료되었습니다.',
  'super_save_iscomplete_19': 'SUPER SAVE 참여가\n완료되었습니다.',
  'credit_sale_iscomplete_18': '외상매도권 참여가\n완료 되었습니다.',
  'super_save_payment_details': 'SUPER SAVE 지급내역',
  'super_save_transaction_registration': 'SUPER SAVE 거래 등록',
  'supersave_corporate_transaction_1':
  '거래 등록 완료 시 등록 정보는 회원정보에 \n업데이트 되며,',
  'supersave_corporate_transaction_2': '담당자의 확인 후 SUPER SAVE 이용이 가능',
  'supersave_corporate_transaction_3': '합니다.',
  'supersave_corporate_transaction_registration_info':
  'SUPER SAVE 법인 거래 등록 안내',
  'super_save_only_requires':
  'SUPER SAVE 첫 이용 시에만 거래 등록이 필요하며 다음\n참여부터는 생략됩니다.',
  'super_save_user_guide': 'SUPER SAVE 이용가이드',
  'super_save_referral_code': 'SUPER SAVE 추천 코드',
  'super_save_when_registration_transaction':
  'SUPER SAVE 법인 거래 등록 시 사업자 등록증과 법인 계좌 등록이 필요합니다.',
  'super_save_corporate_reg': 'SUPER SAVE 법인 거래 등록',
  'super_save_corporate_contact_info': '법인 거래 담당자 정보',
  'super_save_corporate_contact_info_sub': '담당자의 정확한 정보를 등록해주세요.',
  'super_save_corporate_contact_name_label': '담당자 이름',
  'super_save_corporate_contact_name_hint_text': '이름',
  'super_save_corporate_contact_person_in_charge_label': '担当者の連絡先',
  'super_save_corporate_contact_person_in_charge_hint_text': '숫자만 입력',
  'super_save_corporate_identity_verification_cta_label': '본인인증',
  'super_save_corporate_contact_email_label': '담당자 E-mail',
  'super_save_corporate_contact_email_hint_text': '이메일 입력',
  'super_save_corporate_contact_email_cta_label': '이메일 인증',
  'super_save_corporate_next_cta_label': '다음',
  'super_save_corporate_success_title': '법인 거래 등록이 완료되었습니다.',
  'super_save_corporate_success_subtitle':
  '영업일 기준 1일 이내로\n담당자가 등록된 정보를 확인하며\n등록 완료 시 SUPER SAVE가 가능합니다.',
  'swap': '스왑',
  'swap_token': '스왑 토큰',
  'swipe_left_to_next_page': '다음 페이지로 왼쪽으로 스 와이프',
  'take_again': '다시찍기',
  'take_me_to_listings': '목록으로 이동',
  'take_pictures': '사진찍기',
  'ten_k': '만',
  'terms_and_conditions': '이용약관',
  'the_account_application_4':
  '슈퍼세이브 외상거래는 SUT의 현재와 미래 가치를 제대로 반영하여, 상당히 높은 가격에 외상매수 하게 됩니다.',
  'the_account_use_3':
  '슈퍼세이브는 MSQUARE의 실물경제 플랫폼 생태계 확산을 위한 글로벌 유저증가와 결제수단인 SUT의\n실사용 고정매수세 확대를 목표로 합니다.',
  'the_account_use_4':
  'MSQUARE 실물경제 플랫폼 유저 증가속도를 가파른 상승곡선으로 만들어줄 신박한 플랫폼이 바로 슈퍼세이브입니다.',
  'the_application_exceeded_5': '신청가능한도를 초과하였습니다.',
  'the_change_7':
  '- 외상매도 결제대금 지급방식은 선택한 외상매도의 결제대금 지급기간 동안 일일 분할지급 되며, 매주 월요일 주간 정산하여 일괄 지급됩니다. \n - 월요일이 휴일인 경우, 익영업일에 금액 변동없이 \n지급됩니다. ',
  'the_credit_completed_1': '외상매도 신청이 \n완료되었습니다.',
  'the_credit_completed_19': '외상매도 신청이\n완료되었습니다.',
  'msquare_team': 'MSQUARE\n자체 보유 개발팀',
  'msquare_team_1':
  '머스트핀테크는 멀티플랫폼 개발 전문기업으로 MSQUARE의 실물경제 플랫폼 개발을 총괄하고 있습니다.',
  'msquare_team_2': '머스트크루 유튜브 바로가기',
  'ss_inquiry': '전국 슈퍼세이브 문의처',
  'the_message_value_is_empty': '메시지 값이 비어 있습니다.',
  'the_number_krw_1': '이미 SUPER SAVE 거래 등록된 회원입니다.',
  'the_number_processed_38': '탈퇴 신청된 회원입니다 탈퇴 처리 중에는 서비스 이용이 불가능합니다.',
  'the_participation_day_12':
  '참여가능한도는 매일 갱신되며, 매일 지급되는 일일균등지급금 만큼 한도가 복원됩니다.',
  'the_payment_period_2': '결제대금 지급기간 동안 일일 분할지급 되며',
  'the_slips_20':
  '- 거래확인증은 고객 편의를 위해 제공되는 것으로,현금영수증, 매출전표 등 증빙서류로 사용하실 수 없습니다.',
  'there_are_no_search_results': '조회 결과가 없습니다.',
  'there_is_complete_2':
  'SUPER SAVE 참여 가능한 외상매도 신청건이 있습니다. 참여 완료 후 다시 신청해주세요',
  'there_is_complete_20':
  'SUPER SAVE 참여 가능한 외상매도 신청건이 있습니다. 참여 완료 후 다시 신청해주세요',
  'to': '에게',
  'get_email_code': '이메일 코드 받기',
  'get_phone_code': '휴대폰 코드 받기',
  'usdt_code_timout_title': '입력 시간 초과.',
  'usdt_code_wrong_title': '입력 시간 초과.',
  'usdt_code_timout_msg': '@thing를 다시 받으시겠습니까?',
  'text_msg': '문자 메세지',
  'call': '음성 통화',
  'usdt_code_wrong_msg': '인증번호를 다시 확인해주세요.',
  'usdt-resend-title': '문자를 다시 받기 전에 확인해주세요',
  'usdt-recall-title': '음성통화를 다시 받기 전에 확인해주세요',
  'usdt_sms_resend_txt': '휴대폰번호 확인,휴대폰번호가 올바르게 입력되었는지 확인해주세요.;'
      '스팸 메시지 확인,메시지가 스팸으로 분류되어 있는지 확인해주세요.;'
      '통신사 확인,통신사에 문자 수신이 가능한 상태인지 확인해주세요.\n(통신사 차단 서비스, 요금 납부 상태 등)',
  'usdt_voice_recall_txt': '휴대폰번호 확인,휴대폰번호가 올바르게 입력되었는지 확인해주세요.;'
      '스팸 메시지 확인,메시지가 스팸으로 분류되어 있는지 확인해주세요.;'
      '이동통신사 확인,음성통화 수신 가능한 이동통신사인지 확인하세요.\n(통신사 차단 서비스, 요금 납부 상태 등)',
  'email_sms_resend_txt':
  '전화번호/이메일을 확인하시고, 전화번호/이메일이 정확하게 입력되었는지 확인해주세요.;'
      '스팸 메시지를 확인하세요,메시지가 스팸으로 분류되어 있는지 확인해주세요.;'
      '통신사 확인,통신사에 문자 수신이 가능한 상태인지 확인해주세요.\n(통신사 차단 서비스, 요금 납부 상태 등)',
  'usdt_registration_txt':
  'SUPER SAVE USDT 이용 시 타인의 정보도용 방지를 위한 휴대폰 인증이 필요합니다.\n'
      'SUPER SAVE USDT 첫 이용 시에만 거래 등록이 필요하며 다음 참여부터는 생략됩니다.\n'
      '거래 등록 완료 시 등록 정보는 회원정보에 업데이트 되며, 담당자의 확인 후 SUPER SAVE 이용이 가능합니다.',
  'usdt_regist_title': 'SUPER SAVE USDT 거래 등록 안내',
  'usdt_regist': 'SUPER SAVE USDT 등록',
  'usdt_regist_btn': 'SUPER SAVE USDT 거래 등록',
  'usdt_regist_cmplt': 'USDT 거래 등록이 완료되었습니다.',
  'token_transfer': '토큰 전송',
  'topup_credit': '충전/크레딧',
  'total': '총 @length\\건',
  'total_krw_usdt': '합계: 원화+USDT',
  'total_amount': '총액',
  't_total_amount': '합계 금액',
  'total_credit_amount_1': '총 외상매도 결제금액',
  'total_daily_equal_payout': '총 일일균등지급금',
  'show_completed_participations': '거부된/완료된 참여 표시',
  'total_n_cases': '총 @n 건',
  'total_paid_accounts_payable': '총 지급완료 외상대금',
  'total_participants': '전체 참여인원',
  'total_participation_amount': '전체 참여현황',
  'total_participation_amount_1': '전체참여금액',
  'total_participation_history': '전체 참여건수',
  'total_remaining_accounts_payable': '총 잔여 외상대금',
  'total_value': '총 가치',
  'trade_registration': '거래 등록',
  'trading': '거래',
  'transaction_confirm_msg': '귀하의 거래가 성공적으로 승인되었습니다.',
  'transaction_confirmation': '거래확인증',
  'transaction_confirmed': '거래 확인',
  'transaction_detail': '거래 세부 정보',
  'transaction_done': '이미 거래 완료. 다른 QR 코드를 사용하십시오.',
  'transaction_failed': '거래 실패',
  'transaction_history': '거래 내역',
  'transaction_information': '거래정보',
  'transaction_name': '거래명',
  'transaction_number': '거래번호',
  'transaction_registration_participation_3':
  'SUPER SAVE 첫 이용 시에만 거래 등록이 필요하며 다음 참여부터는 생략됩니다.',
  'transaction_request': '트랜잭션 요청',
  'transaction_type': '거래유형',
  'transaction_timeout': '거래 시간 초과, 다시 시도해 주세요.',
  'transaction_unsuccessful': '거래가 실패하였습니다.',
  'transfer': '외매권 양도 전송',
  'transfer_to_super_save_wallet': 'SUPER SAVE 지갑으로 전송',
  'transmission_quantity': '전송수량',
  'try_again_later': '나중에 다시 시도 해주십시오',
  'try_again_msg_1': '다시 시도해주세요.',
  'try_again_msg_2': '의사록',
  'tx_id_cannot_be_blank': 'TX ID는 비워둘 수 없습니다.',
  'enter_valid_tx_id': '유효한 TXID를 입력해야 합니다.',
  'txid_input_again_1': 'TXID 입력시간이 초과되었습니다. 다시 시도해주세요.',
  'unlock_wallet': '사용자의 신원을 확인',
  'update_billing_details': '결제 세부 정보 및 주소 업데이트',
  'update_password': '비밀번호 업데이트',
  'update_payment_method': '카드 연결하기',
  'usdt': 'USDT',
  'use_password': '비밀번호 사용',
  'user': '사용자',
  'user_': '사용자:',
  'user_details': '사용자 세부정보',
  'user_guide': '이용가이드',
  'user_id': '유저 아이디',
  'user_name': '사용자 이름',
  'username': '사용자 이름',
  'username_copied': '사용자 이름이 클립보드에 복사됨',
  'email_copied': '이메일이 클립보드에 복사됨',
  'address_copied': '주소가 클립보드에 복사되었습니다.',
  'check_store_info': '가맹점 정보 확인하기',
  'user_id_copied': '사용자 ID가 클립보드에 복사됨',
  'view_all': '모두 보기',
  'waiting_for_approval': '승인 대기',
  'wallet': '지갑',
  'wallet_address': '지갑 주소',
  'wallet_id_copied': '지갑 주소가 클립보드에 복사되었습니다',
  'wallet_id_copied_to_clipboard': '지갑 주소가 클립보드에 복사되었습니다',
  'wallet_request': '월렛 요청',
  'wallet_connection_request': '월렛 연결 요청',
  'wallet_successfully_terminated': '지갑이 성공적으로 종료되었습니다.',
  'wallet_termination': '지갑 삭제',
  'wallet_cannot_termination':
  'SUPER SAVE 등록이 되어 있기 때문에 지갑을 해지할 수 없습니다.',
  'wallet_termination_failed': '지갑 종료 실패',
  'wallet_termination_screen': '지갑 종료',
  'want_to_logout': '로그아웃하시겠습니까',
  'sec_threat': '보안 위협',
  'we_detected_sec_rel':
  '보안 위협이 감지되어 지금은 앱 사용을 허용할 수 없습니다. 문제를 해결하고 앱을 다시 시작해 보세요.',
  'case_code': '케이스 코드: @c',
  'we_are_again_29': '귀하의 응답을 받을 수 없습니다. 다시 시도하십시오.',
  'weekly_settlement_monday_3': '매주 월요일 주간 정산하며 지급됩니다.',
  'welcome': '어서오세요.',
  'welcome_back': '다시 오신 것을 환영합니다',
  'what_is_super_save': 'SUPER SAVE란?',
  'when_msq_voluntary_7':
  'MSQ를 슈퍼세이브 지갑에 전송하는 시점 거래는 완료되는 것이며, 소유권은 MSQUARE 본사로 이전되며 소유권 행사 또한 자율권한입니다.',
  'when_transaction_charge_4':
  '거래 등록 완료 시 등록 정보는 회원정보에 업데이트 되며, 담당자의 확인 후 SUPER SAVE 이용이 가능합니다.',
  'when_using_tax_2':
  'SUPER SAVE 이용 시 타인의 정보도용 방지 및 지급금 입금,양도소득세 정산 등을 위한 본인인증 및 계좌등록이 필요합니다.',
  'When_using_supersave':
  'SUPER SAVE 이용 시 타인의 정보도용 방지 및 지급금 입금,\n양도소득세 정산 등을 위한 본인인증 및 계좌등록이\n필요합니다.',
  'withdraw': '출금',
  'won': '원',
  'won_suffix': '원권',
  'wrong_password': '잘못된 비밀번호를 입력하셨습니다',
  'year': '년',
  'yes': '예',
  'you_agree_etc_14':
  '외상대금을 현금 또는 그와 동일한 가치의 것(금, 쌀, 코인 등)으로 지불가능함에 동의합니다.',
  'you_can_apply_from_1_million_krw': '@from 부터 신청 가능합니다.',
  'you_can_have_a_look_at_your_ad’s_on_your_listings_page':
  '목록 페이지에서 광고를 볼 수 있습니다.',
  'you_can_krw_6': '@of 단위로 신청할 수 있습니다.',
  'you_have_created_an_ad': '광고를 만들었습니다.',
  'you_have_no_cumulative_balance': '누적 잔액이 없습니다.',
  'you_sure': '한번 더 확인해주세요',
  'your_order_has_been_placed': '주문이 접수되었습니다',
  'add_p2u_store_info': '지도를 클릭하여 선택할 수도 있습니다.',
  'Andong': '안동시',
  'Ansan': '안산시',
  'Anseong': '안성시',
  'Anyang': '안양시',
  'Asan': '아산시',
  'Boryeong': '보령시',
  'Bucheon': '부천시',
  'Busan': '부산광역시',
  'Changwon': '창원시',
  'Cheonan': '천안시',
  'Cheongju': '청주시',
  'Chuncheon': '춘천시',
  'Chungju': '충주시',
  'Daegu': '대구광역시',
  'Daejeon': '대전광역시',
  'Dangjin': '당진시',
  'Dongducheon': '동두천시',
  'Donghae': '동해시',
  'Gangneung': '강릉시',
  'Geoje': '거제시',
  'Gimcheon': '김천시',
  'Gimhae': '김해시',
  'Gimje': '김제시',
  'Gimpo': '김포시',
  'Gongju': '공주시',
  'Goyang': '고양시',
  'Gumi': '구미시',
  'Gunpo': '군포시',
  'Gunsan': '군산시',
  'Guri': '구리시',
  'Gwacheon': '과천시',
  'Gwangju': '광주광역시',
  'Gwangju, Gyeonggi': '광주시',
  'Gwangmyeong': '광명시',
  'Gwangyang': '광양시',
  'Gyeongju': '경주시',
  'Gyeongsan': '경산시',
  'Gyeryong': '계룡시',
  'Hanam': '하남시',
  'Hwaseong': '화성시',
  'Icheon': '이천시',
  'Iksan': '익산시',
  'Incheon': '인천광역시',
  'Jecheon': '제천시',
  'Jeongeup': '정읍시',
  'Jeonju': '전주시',
  'Jeju': '제주시',
  'Jinju': '진주시',
  'Naju': '나주시',
  'Namyangju': '남양주시',
  'Namwon': '남원시',
  'Nonsan': '논산시',
  'Miryang': '밀양',
  'Mokpo': '목포시',
  'Mungyeong': '문경시',
  'Osan': '오산시',
  'Paju': '파주시',
  'Pocheon': '포천시',
  'Pohang': '포항시',
  'Pyeongtaek': '평택시',
  'Sacheon': '사천시',
  'Sangju': '상주시',
  'Samcheok': '삼척시',
  'Sejong': '세종특별자치시',
  'Seogwipo': '서귀포시',
  'Seongnam': '성남시',
  'Seosan': '서산시',
  'Seoul': '서울특별시',
  'Siheung': '시흥시',
  'Sokcho': '속초시',
  'Suncheon': '순천시',
  'Suwon': '수원시',
  'Taebaek': '태백시',
  'Tongyeong': '통영시',
  'Uijeongbu': '의정부시',
  'Uiwang': '의왕시',
  'Ulsan': '울산광역시',
  'Wonju': '원주시',
  'Yangju': '양주시',
  'Yangsan': '양산시',
  'Yeoju': '여주시',
  'Yeongcheon': '영천시',
  'Yeongju': '영주시',
  'Yeosu': '여수시',
  'Yongin': '용인시',
  'Gijang-gun': '기장군',
  'Dalseong-gun': '달성군',
  'Gunwi-gun': '군위군',
  'Ganghwa-gun': '강화군',
  'Ongjin-gun': '옹진군',
  'Ulju-gun': '울주군',
  'Gapyeong-gun': '가평군',
  'Yeoncheon-gun': '양평군',
  'Hongcheon-gun': '홍천군',
  'Hoengseong-gun': '횡성군',
  'Yeongwol-gun': '영월군',
  'Pyeongchang-gun': '평창군',
  'Jeongseon-gun': '정선군',
  'Cheorwon-gun': '철원군',
  'Hwacheon-gun': '화천군',
  'Yanggu-gun': '양구군',
  'Inje-gun': '인제군',
  'Goseong-gun (Gangwon-do)': '고성군(강원특별자치도)',
  'Yangyang-gun': '양양군',
  'Boeun-gun': '보은군',
  'Okcheon-gun': '옥천군',
  'Yeongdong-gun': '영동군',
  'Jeungpyeong-gun': '증평군',
  'Jincheon-gun': '진천군',
  'Goesan-gun': '괴산군',
  'Eumseong-gun': '음성군',
  'Danyang-gun': '단양군',
  'Geumsan-gun': '금산군',
  'Buyeo-gun': '부여군',
  'Seocheon-gun': '서천군',
  'Cheongyang-gun': '청양군',
  'Hongseong-gun': '홍성군',
  'Yesan-gun': '예산군',
  'Taean-gun': '태안군',
  'Wanju-gun': '완주군',
  'Gochang-gun': '고창군',
  'Buan-gun': '부안군',
  'Imsil-gun': '임실군',
  'Sunchang-gun': '순창군',
  'Jinan-gun': '진안군',
  'Muju-gun': '무주군',
  'Jangsu-gun': '장수군',
  'Damyang-gun': '담양군',
  'Gokseong-gun': '곡성군',
  'Gurye-gun': '구례군',
  'Goheung-gun': '고흥군',
  'Boseong-gun': '보성군',
  'Hwasun-gun': '화순군',
  'Jangheung-gun': '장흥군',
  'Gangjin-gun': '강진군',
  'Haenam-gun': '해남군',
  'Yeongam-gun': '영암군',
  'Muan-gun': '무안군',
  'Hampyeong-gun': '함평군',
  'Yeonggwang-gun': '영광군',
  'Jangseong-gun': '장성군',
  'Wando-gun': '완도군',
  'Jindo-gun': '진도군',
  'Sinan-gun': '신안군',
  'Uiseong-gun': '의성군',
  'Cheongsong-gun': '청송군',
  'Yeongyang-gun': '영양군',
  'Yeongdeok-gun': '영덕군',
  'Cheongdo-gun': '청도군',
  'Goryeong-gun': '고령군',
  'Seongju-gun': '성주군',
  'Chilgok-gun': '칠곡군',
  'Yecheon-gun': '예천군',
  'Bonghwa-gun': '봉화군',
  'Uljin-gun': '울진군',
  'Ulleung-gun': '울릉군',
  'Haman-gun': '함안군',
  'Geochang-gun': '거창군',
  'Changnyeong-gun': '창녕군',
  'Goseong-gun (Gyeongsangnam-do)': '고성군(경상남도)',
  'Hadong-gun': '하동군',
  'Hapcheon-gun': '합천군',
  'Namhae-gun': '남해군',
  'Hamyang-gun': '함양군',
  'Sancheong-gun': '산청군',
  'Uiryeong-gun': '의령군',
  'Yangpyeong-gun': '양평군',
  'dob': '주민등록번호',
  'phone_company': '통신사',
  'input_number_error': '입력은 비워둘 수 없습니다.',
  'otp_error': '인증번호는 6자리여야 합니다.',
  'offshore_labor_projects': '해외 인력 수급 프로젝트',
  'wait_for_release': '출시대기',
  'resend': '다시 보내기',
  'recall': '다시 전화 인증',
  'call_me': '전화로 인증',
  'sms_me': '문자로 인증',
  'sms_sent': '곧 SMS를 받게 됩니다.',
  'call_sent': '곧 음성 통화를 받게 됩니다.',
  'sensitive_information_prompt': '민감정보는 개인정보보호법에 따라 암호화하여 안전하게 보호됩니다.',
  'select_phone_company': '통신사',
  'enter_phone_number': '휴대폰번호',
  'enter_date_birth': '생년월일을 입력하세요',
  'enter_detail': '이름을 입력해주세요',
  'input_field_error': '입력 필드는 비워둘 수 없습니다.',
  'name_error': '이름은 비워둘 수 없습니다.',
  'dob_error': '생년월일은 비워둘 수 없습니다.',
  'number_error': '숫자는 비워둘 수 없습니다.',
  'check_phone_number': '전화번호를 확인하세요',
  'check_phone_number_sub_text': '휴대폰 번호를 입력했는지 확인해주세요',
  'check_spam': '스팸 메시지 확인',
  'check_spam_sub_text': '해당 메시지가 스팸으로 분류되어 있는지 확인해주세요',
  'check_carrier': '이동통신사가 문자 메시지를 받을 수 있는지 확인하세요.',
  'check_before_resend': '다시 문자 보내기 전에 확인해주세요',
  'enter_verification_code': '인증코드를 입력하세요',
  'verification_failure': '확인 실패',
  'input_field_validation_error': '입력 검증 실패',
  'verification_code_error': '인증 번호가 일치하지 않습니다.',
  'verification_code_error_description': '인증 번호를 다시 확인해 주세요.',
  'register_param_incorrect': '제공하신 정보 중 일부가 정확하지 않습니다. 다시 확인해 주세요.',
  'add_referral': '슈퍼세이브를 나에게 소개한 사람 (선택 사항)',
  'add_referral_required': '슈퍼세이브를 나에게 소개한 사람 (필수 입력)',
  'add_referral_is_required': '추천 코드가 필요합니다.',
  'referral_code': '슈퍼세이브를',
  'referral_code_sub_title': '나에게 소개한 사람 추가',
  'type_your_referral_code': '슈퍼세이브를 나에게 소개한 사람 코드를 입력하세요.',
  'referral_code_error': '유효하지 않은 코드, 5자리 숫자여야 합니다',
  'referral_code_api_error': '잘못된 코드입니다. 다시 확인해 주세요.',
  'referral_phone_api_error': '전화번호가 잘못되었습니다. 다시 확인해 주세요.',
  'referred_by': '해당 추천인 정보:',
  'add': '추가하기',
  'please_confirm': '확인 요청 드립니다',
  'grant': '부여하기',
  'approve_failure': '승인 거절',
  'referral_code_title': '추천인 코드가',
  'added_successfully': '성공적으로 등록되었습니다.',
  'add_percentage': '퍼센트 추가',
  'how_much_percentage': '얼마나 줄 건가요?',
  'confirmation_text':
  '@name님이 외상 매도를 올바르게 처리할 것입니다. 결정이 내려지면 변경하거나 취소할 수 없습니다. 확실합니까?',
  'search_by_phone_number': '전화번호로 검색하세요.',
  'select_transfer_percentage': '양도할 권리 금액을입력하세요.',
  'remained_amount_after_transfer': '양도 후 남은 나의권리 금액입니다.',
  'phone_code': '전화번호',
  'invalid_phone_code': '유효하지 않습니다! 전화번호가 올바르지 않습니다.',
  'code_tab': '코드',
  'deny': '거절하기',
  'dont_show_again': '다시 표시하지 않기',
  'referrals_not_zero': '추천은 0%가 될 수 없습니다.',
  'total_percentage_should_be_100': '총 백분율은 100%와 같아야 합니다.',
  'code_already_exists': '추천 코드가 이미 존재합니다.',
  'card_duplicate':
  '이미 @index 정보를 입력했기 때문에 또 다시 입력 하실 필요없이 적용됩니다. 만약 다른 정보를 입력하고 싶다면 아래 버튼을 눌러주세요.',
  'invalid_registration_number': '유효하지 않은 주민등록번호',
  'invalid_name': '잘못된 이름이 제공되었습니다',
  'invalid_number': '입력한 전화번호가 잘못되었습니다',
  'credit_sale_right': '사용하지 않은 외상매도권이 있습니다. (%credit_sale%)',
  'congratulations': '축하합니다!',
  'go_to_credit_sale_right': '내용 확인하러 가기',
  'go_to_check': '내용 확인하러 가기',
  'move_to_check': '확인하려면 이동',
  'super_saver_need_to_complete': ' 완료가 필\n요합니다.',
  'waiting_for_response': '응답 대기 중',
  'active_inquiry': '활성 문의',
  'solved': '해결됨',
  'hold_status': '잡고 있다',
  'search_for_inquiry': ' 문의 검색',
  '1:1inquiry': '1:1 문의',
  'Hold': '잡고 있다',
  'by_status': '상태별',
  'by_category': '카테고리별',
  'status': '상태:',
  'p2p_mining_inquiry': 'P2U 채굴 문의',
  'select_category': '카테고리 선택',
  'attachment': '첨부 파일',
  'browse_file': '파일 찾아보기',
  'create_new_inquiry': '새 문의 생성',
  'message_here': '메시지를 입력하세요',
  'general': '일반',
  'bug': '버그',
  'p2u': 'P2U',
  'p2umining': 'P2U 채굴',
  'inquiry_dialog_response':
  '문의를 제출해 주셔서 감사합니다. 귀하의 사례를 검토하고 다음 24-48시간 이내에 답변을 드리겠습니다.',
  'inquiry_track_detail': '1:1 문의 화면에서 문의를 추적할 수 있습니다.',
  'track_inquiry': '문의 추적하기',
  '1:1inquiry_received': '1:1 문의를 받았습니다',
  'inquiry_anouncement': '1:1 문의에 답변이 도착했습니다.',
  'inquiry_empty': '최근 문의가 없습니다',
  'title': '제목',
  'inquiry_created_successfully': '문의가 성공적으로 생성되었습니다',
  'subject_error': '제목은 비워 둘 수 없습니다',
  'category_error': '카테고리는 비워 둘 수 없습니다',
  'content_field_error': '뭔가 잘못되었습니다',
  'something_went_wrong': 'S뭔가 잘못되었습니다',
  'Active': '활성',
  'Solved': '해결됨',
  'Waiting': '대기 중',
  'General': '일반',
  'Bug': '버그',
  'SUPER SAVE': 'SUPER SAVE',
  'P2U': 'P2U',
  'P2U Mining': 'P2U 채굴',
  'super_save_is_confirmed': '%super_save_popup%가 승인되었습니다.',
  'super_save_popup': '슈페세이브',
  'credit_sale_right_created': '외상매도권이\n발생했습니다.',
  'super_save_awaits_completion': '슈페세이브 완료가 필요합니다.',
  'commitment_document': '확약서 첨부하기',
  'please_add_commitment_document': '아래버튼을 눌러서 확약서를 첨부해주세요',
  'add_commitment_document': '여기에서 확약서 문서를 추가하세요',
  'your_card_will_be_deleted':
  '해결방법: 카드사 정책 때문에 카드 등록이 삭제가 될 예정입니다 카드회사에 가서 패스워드를 바꾸세요. 반드시 비밀번호는 복잡하게 설정 해야합니다.',
  'your_added_card_deleted': '추가한 카드가 삭제되어 다시 추가해야 합니다.',
  'confirmation_letter': '확약서',
  'read_the_content': '아래의 내용을 읽고',
  'confirmation_terms':
  '본인 또는 본인의 가족이 슈퍼세이브 신규가입시, 소개자(외상매도권자)가 가족이 아닐 경우, 외부 소개자에게 50%이상 외매권을 지정할 것이며, 약속 위반시 소개자 삭제 또는 변경에 동의합니다.',
  'confirmation_terms_1': '(단, 추천인이 복수일 경우 외매권의 비율은 사용자가 지정한 비율로 한다.)',
  'introducer': '소개자: ',
  'introduced_by': '참여자: ',
  'enrollment_data': '가입일: ',
  'crop': '저장',
  'please_crop_image': '이미지를 잘라주세요',
  'failed_during_cropping_image': '이미지를 자르는 중 실패했습니다.',
  'the_image_too_small': '이미지가 너무 작습니다.',
  'add_p2u_store_updated_successfully':
  '귀하의 P2U 스토어가 성공적으로 업데이트되었습니다.',
  'grant_location_permission':'위치 권한을 부여하고 화면을 다시 열어주세요.',
  'p2u_store_deleted_successfully': '스토어가 성공적으로 삭제되었습니다.',
  'p2u_store_deleted_unsuccessfully': '스토어를 삭제할 수 없습니다.',
  'delete': '삭제',
  'undo': '실행 취소',
  'hide_card_confirm': '이 카드를 숨기시겠습니까?',
  'open_super_save': '슈퍼세이브 보러가기',
  'complete_super_save': '슈퍼세이브 완료하기',
  'request_credit_sale_right': '외상매도권 신청하기 ',
  'sut_credit_sale_right_issued': 'SUT 외상매도권이 도착했습니다.',
  'invalid_email_or_id': '이메일 주소 또는 ID가 올바르지 않습니다.',
  'participation_transferred': '참여 이전'
};