part of 'languages.dart';

const Map<String, String> _zhCH = {
  'guide_title_1': '슈퍼세이브 외상거래 설명회',
  'guide_line_1_1': '地点\t韩国首尔松坡区松坡大道167号文亭站泰拉大厦A座1303室',
  'guide_line_1_2': '时间安排\t由于每隔一周举办一次，请查看详细的信息发布会时间表。\n请联系客服。',
  'guide_line_1_3': '课程时间\t2-3 小时',
  'guide_title_2': 'M廣場\n社區\n全國辦公室',
  'guide_line_2_1': '一山\t高阳市一山西区中央路1765 1楼\n010-7987-5995',
  'guide_line_2_2': '广津区\t首尔特别市广津区灵洞路7号汉江公园大厦314号\n010-4965-3910',
  'guide_line_2_3': '始兴\t始兴市协路281号Megapolis C栋118号\n010-3731-7553',
  'guide_line_2_4': '唐津\t忠清南道唐津市邑内洞 531-4 Venture Week 201 室\n010-8567-8084',
  'guide_line_2_5': '大田\t大田西区炭房路 26 Sufelis #204\n010-2825-8652',
  'guide_line_2_6': '光州\t光州广域市西区尚武坪花路 89, #413\n010-3104-2468',
  'guide_line_2_7': '束草\t束草市中央路121街28 Centum公园\n乐天电影院 134 室\n010-7621-5856',
  'guide_line_2_8': '水原\t水原市灵通区三星路 253 Ace Smart\n灵通知识产业中心914室\n010-6654-8523',
  'guide_line_2_9': '龙仁\t龙仁市器兴区冬柏竹田大路341\n冬柏医药塔B104\n010-4013-0984',
  'guide_line_2_10': '浦项\t浦项市北区二东路 69 德良大厦 402 室\n010-3500-8551',
  'guide_line_2_11': '釜山\t釜山广域市神区东城路 137\n西面东原办公楼 1202 室\n010-2780-8699',
  'guide_line_2_12': '昌原\t昌原市义昌区沙林洞 161-1 现代\n太阳建筑广场F座203室\n010-3747-1747/ 070-8657-4717',
  'guide_line_2_13': '광양\t全罗南道光阳市九马路 61 号 2 层\n010-3993-2667',
  'guide_line_2_14': '세종\t世宗市世宗区罗城洞 792 NS Tower 805 号\n010-6425-8819',
  'guide_line_2_15': '진주\t晋州市忠武公 69-3 号 Wingtower B 座 1104 室\n010-9301-0803',
  'guide_line_2_16': '사천\t四川省遂川县中洞面乌山路 50-53 号前和村 2 楼\n010-3780-8215',
  'guide_title_3': '超级节省申请流程',
  'home_ban_title': '世界第一',
  'home_ban_subtitle': '基于区块链实体经济的币币外汇平台',
  'participation_complete_first': '现在就想加入 SUPER SAVE？',
  'participation_complete_second': '点击下面的加入 SUPER SAVE！',
  'join_super_save': '加入 SUPER SAVE',
  'cash_transfer_capture_file_missing': '现金转账捕获文件丢失。',
  'coin_transfer_capture_file_missing': '硬币传输捕获文件丢失。',
  'total_percentage_cannot_be_more_than_100': '总百分比不能大于 100%',
  'new_balance': '新百伦',
  'previous_balance': '上期余额',
  'reason': '原因',
  'this_transaction_old_than_card_added': '该交易的时间早于卡的添加时间。',
  'this_transaction_cash_dispenser_service': '此交易为现金出纳服务。',
  'this_transaction_was_mined_by_another_user': '该交易由另一位用户挖掘。',
  'mining_time_is_not_within_threshold': '采矿时间不在阈值周期内。',
  'skip': '跳过',
  'skip_phone': '跳过',
  'skip_phone_msg': '如果跳过，您的 SUPER SAVE 注册必须获得批准，才能获得 P2U 空投。',
  'system_problem': '部分服务出现问题',
  'code': '代码',
  'reported': '已报道',
  'verify': '核实',
  'verify_email': '查看你的电子邮件',
  'verify_phone': '验证电话号码',
  'phone': '电话号码',
  'email': '电子邮件',
  'mining_failed': '挖矿失败',
  'p2u_mining_not': 'P2U挖矿未完成！',
  'card_issue': '您的@cardName有问题，您必须先解决此问题才能继续挖矿。',
  'i_read': '我已阅读并理解',
  'you_are_corporate_member': '您是企业会员。',
  'you_are_individual_member': '您是个人会员。',
  'account_holder_name': '账户持有人姓名',
  'enter_account_holder_name': '输入账户持有人姓名',
  'person_charge_number': '负责人联系',
  'enter_name': '输入名字',
  'phone_number_must_be_11_digits': '电话号码必须是11位数字',
  'member_type': '会员类型',
  'indv_member': '个人会员',
  'corp_member': '企业会员',
  'corp_popup': '企业会员无法查看个人交易。',
  'indv_n_corp_member': '个人 / 企业 会员',
  'mined_by': '开采者',
  'transaction_draft_tooltip': '您将看到所有信息，包括错过的 P2U 收入。',
  'mining_denied': '拒绝采矿！',
  'missed_threshold_period': '你错过了临界期！',
  'company_policy': '公司政策',
  'use_inquiry': '如果有查询，请使用 1:1 查询菜单。',
  'details': '详细信息',
  'card_number': '卡号',
  'store': '商店',
  'mining_percentage': '采矿百分比',
  'earned_p2u': '赚取的 P2U',
  'threshold': '到期日',
  'day(s)': '天数',
  'payment_status': '付款状态',
  'mining_threshold': '挖矿门槛',
  'paid': '已付款',
  'refund': '退款',
  'affiliated': '附属',
  'not_affiliated': '无隶属关系',
  'enable_fingerprint_auth': '启用指纹认证',
  'finger_auth_enabled': '指纹认证开启成功',
  'finger_auth_fail': '指纹认证取消',
  'forgot_pass': '忘了密码？',
  'reset_pass_header_text': '要重置密码，请输入新密码和通过电子邮件发送的 OTP。',
  'reset_pass_header_text_phone': '要重置密码，请输入新密码和手机上发送的 OTP。',
  'enter_6_digit_otp': '输入 6 位 OTP',
  'reset_password': '重置交易密码',
  'apply': '申请',
  'discount': '割引率',
  'add_payment_method': '⏳ 连接卡',
  'add_payment_method_error': '连接卡',
  'request_id_copied': '请求 ID 已复制',
  'request_id': '请求ID',
  'super_save_ownership_received': '您已成功收到 SUPER SAVE 所有权。',
  'super_save_transfer_success': 'SUPER SAVE 所有权转移成功。',
  'enter_valid_email_address': '请输入有效的电子邮件地址',
  'email_address_cannot_be_empty': '电子邮件值不能为空',
  'transfer_of_ownership_super_save_request':
  '这会将 SUPER SAVE 请求的所有权转移给新用户',
  'new_user_email': '新用户邮箱',
  'un_authorized': '未授权\n请重新登录',
  'enter_email_address': '输入电邮地址',
  'submit': '提交',
  'transfer_ownership': '所有权转让',
  'metastar_clients': '元斯塔客户',
  'waiting': '等候',
  'complete_buying': '完整购买 @token',
  'buy_token': '购买@token',
  'sell_token': '出售@token',
  'no_p2p_orders': '@token 没有 @type 订单',
  'p2p_order_conv': '每个 @txToken @rate @token',
  'complete_p2p_trade': '完成P2P贸易',
  'transfer_to_your_accnt': '将转入您的钱包。',
  'select_wallet_to_pay': '选择钱包进行支付',
  'connect_wallet_to_pay': '连接钱包进行支付',
  'you_will_pay': '您将支付',
  'with_your_wallet': '用您的钱包',
  'amount_n_fee': '(金额 + 费用)',
  'promotion_period': '正值促销期!',
  'fee_will_not_be_charged': '\n不收取任何费用。',
  'you_need_pay': '你需要支付一个',
  'a': 'A',
  'service_fee': '@val% 服务费',
  'of_amnt_4_tx': '\n交易的@token 金额。',
  'will_add_to_amnt': '将被添加到\n@token 您将支付的金额。',
  'complete': '完全的',
  'enter_wallet_address_for_p2p_sell': '输入您想要\n接收@token的钱包地址：',
  'enter_wallet_address': '输入钱包地址',
  'will_be_charged_from_bal': '将从您的 @token 余额\n中扣除',
  'continue': '继续',
  'today': '今天',
  'wallet_withdrawal_completed': '完成@token钱包取款',
  'notification_save': '节省',
  'tx_already_done': '交易已经完成',
  'points': '点数',
  'current_location': '当前位置',
  'location_permission': '位置许可',
  'no_img_avail': '没有可用的图像',
  'location': '位置',
  'store_near_your_location': '商店靠近您的位置',
  'stores_in_city': '@city 中的商店',
  'no_stores_found': '未找到商店',
  'search_by_address': '按名称搜索',
  'select_city': '选择市/县',
  'city': '市/县',
  'search_city': '搜索市/县',
  'all_cities': '所有城市',
  'city_not_found': '未找到城市',
  'copied': '已复制',
  'bio_disable_fail': '禁用指纹失败',
  'bio_disable_success': '禁用指纹成功',
  'set_bio_auth': '设置指纹验证',
  'select_wallet': '选择钱包',
  'gps_required': '需要 GPS',
  'no_store_found': '没有找到商店',
  'gps_msg': '请打开GPS搜索您附近的商店',
  'restart_now': '现在重启',
  'update_avail': '新更新准备就绪',
  'ota_msg': '应用已成功更新至 @version 版本，请重启使用新版本',
  'User rejected the transaction': '您已经拒绝了该交易。',
  'User rejected methods': '您已拒绝连接请求。',
  'tx_req_sent_check_wallet': '交易请求已发送，请检查您的钱包。',
  'tx_in_progress': '交易进行中',
  'wallet_not_exist': '没有找到这样的钱包',
  'super_save_tx': '超级节省交易',
  'search': '搜索',
  'other_wallets': '其他钱包。。。',
  'wallet_connection': '@token钱包连接',
  'tx_fail': '交易失败',
  'tx_success': '交易成功',
  'tx_id_received': '已收到交易 ID。',
  'btn_desc': '按钮说明',
  'resident_registration': '居民登记',
  'foreign_registration': '国外注册',
  'reg_only_seven_digits': '注册必须只有 7 位数字',
  'plz_select_your_country': '请选择您所在的国家/地区',
  'plz_select_country_code': '请选择您的国家/地区代码',
  'wallet_withdrawal': '钱包提款',
  'select_wallet_for_tx': '选择用于交易的钱包',
  'and': '和',
  'plz_send_msq_for_credit_sale':
  '请发送您申请信用销售的@other@and@deposit_token。',
  'plz_send_deposit_for_credit_sale':
  '发送您申请的 @num_of_deposit_token @deposit_token./n 您将被批准 @total_payout_amount @payment_currency.',
  'plz_send_deposit_for_super_save':
  '发送您申请的 @num_of_deposit_token @deposit_token./n 您将被批准 @total_payout_amount @payment_currency.',
  'participate_wallet_address': '@token 存款地址',
  'enter_transmit_txid': '输入 @token 交易散列',
  'no_image_found': '未找到图像',
  'credit_sale_tool_tip': '价格取决于场外交易市场，并且可能会因大宗交易解决方案而发生变化。',
  'change': '更改',
  'go_back': '回去',
  'con_success': '连接成功',
  'con_fail': '连接失败',
  'wallet_con_success': '钱包连接成功',
  'wallet_con_req': '钱包连接请求',
  'wallet_con_req_done': '钱包连接请求已经完成',
  'wallet_con_req_received': '请求钱包连接',
  'wallet_con_req_warning': '请确保用户正确无误。',
  'currency': '货币',
  'default': '默认',
  'change_currency': '更改货币',
  'change_token': '更改令牌',
  'deposit_wallet': '存款钱包',
  'plz_provide_reason_txtbox': '请在文本框中提供原因',
  'charge': '收费',
  'bank_fee': '银行手续费',
  'new_connected_wallet_added': '添加了新的连接钱包',
  'wallet_deleted': '连接的钱包已成功删除',
  'my_connected_wallets': '我的互联钱包',
  'add_connected_wallet': '添加连接的钱包',
  'connected_wallet': '连接钱包',
  'delete_wallet': '删除钱包',
  'main_wallet_not_del': '主钱包无法删除',
  'set_main_wallet': '设置为主钱包',
  'main_connected_wallet_changed': '主要连接的钱包已更改',
  'pls_reg_a_wallet': '请注册钱包。',
  'wallet_balance': '钱包余额',
  'enter_your_wallet': '输入你的钱包',
  'wallet_id_length_check': '您必须输入有效的 USDT (Polygon Network) 钱包地址。',
  'add_wallet': '添加钱包',
  'wrng_wallet_id': '钱包地址不正确。',
  'align_area_20': '↖️ 将卡片与方框区域对齐。',
  'box_19': '↕️ ↔️ 匹配盒子周围的区域。',
  'hold_on_here': '👀 坚持住',
  'its_done': '🆗✅完成了',
  'pic_taken': '✅拍摄的照片',
  'pic_selected': '✅ 照片已选定',
  'invalid_qr_code': '无效的二维码',
  'msq_lock_vol': '资产状态',
  'otc_msqx_market_cap': 'MSQ OTC, MSQX 市值',
  'description': '描述',
  's_trust_mem_price': '超信会员价1@token=@amount @currency',
  'p2u_field_label': '额外销售申请P2U数量',
  'otc_msqx_market_cap_tooltip': '场外交易市值\nMSQ 场外持股市值 + MSQX 持股市值',
  'g_quantity': '公司持有数量',
  'current_price': '时价',
  'g_market_cap': '公司控股市值',
  'otc_market_cap': '场外市场价格',
  'otc_market_cap_tooltip': 'OTC 当前价格',
  'otc_g_market_cap': 'MSQ、MSQX 市值',
  'otc_g_market_cap_tooltip': 'MSQ 控股市值 + MSQX 控股市值',
  'coming_soon': '即将到来',
  'capture_the_image_before': '拍摄之前的图像',
  'captured_image': '捕获的图像',
  'fail': '失败',
  'put_the_card_in_the_box': '将卡放入盒子中',
  'there_is_image_21': '所选图像中没有身份证。',
  'transfer_credit': '转移 @token',
  'enter_recipient_mail': '输入收件人电子邮件',
  'enter_your_amount': '输入您的金额',
  'token_transferred': '代币已转让',
  'token_not_transferred': '代币未转移',
  'alert': '使警觉',
  'please_unfold': '请展开手机以使用相机',
  'select_photo': '选择照片',
  'monday': '星期一',
  'tuesday': '星期二',
  'wednesday': '星期三',
  'thursday': '星期四',
  'friday': '星期五',
  'saturday': '星期六',
  'sunday': '星期日',
  'january': '1月',
  'february': '2月',
  'march': '3月',
  'april': '4月',
  'may': '5月',
  'june': '6月',
  'july': '7月',
  'august': '8月',
  'september': '9月',
  'october': '10月',
  'november': '11月',
  'december': '12月',
  'won_transfer_title': '@bankname 我们发送 1 韩元',
  'confirm_won_auth_title': '请输入您的验证码的3位数字（不包括MSQ）',
  'verification_number': '验证码',
  'authenticate_with_different_account': '使用不同账户进行身份验证',
  'enter_verification_number': '3 位数验证码',
  'supersave_registration_at_add_bank_account': '要添加银行账户，您必须进行超级省钱注册。',
  'otp_length_warning': '验证码必须为 3 位数。',
  '100_million_krw': '+1亿',
  '100_million_krw_br': '+1\n亿',
  '10_million_krw': '+1000万韩元',
  '10_million_krw_br': '+1000\n万韩元',
  '10k_usdt': '+10000 USDT',
  '100k_usdt': '+100000 USDT',
  '100_thousand_krw': '+10万韩元',
  '100_thousand_krw_dialog': '+10万韩元',
  '100_thousand_krw_br': '+10\n万韩元',
  '100_thousand_krw_dialog_br': '+10\n万韩元',
  '1_million_krw': '+100万韩元',
  '1_million_krw_br': '+100\n万韩元',
  '1_k_usdt': '+1000 USDT',
  '100_usdt': '+100 USDT',
  '211_88th_seoul_18': '韩国首尔松坡区松坡大路 167 号 A 洞 917 号',
  'x_days_y_perc': '@x天(@y%)',
  'Amount': '数量',
  'entitlement_amount': '补助金额',
  'Buy': '购买',
  'change_log': '更改日志',
  'Buying': '购买',
  'Fee': '费用',
  'My_Assets': '我的资产',
  'Price': '价格',
  'Sell': '卖',
  'Selling': '卖',
  'Token': '令牌',
  'Tokens': '代币',
  'total_balance_in': '总余额 ',
  'user_canceled': '我取消申请',
  'sendersut': '发件人',
  'auto': '自动',
  'manual': '手动',
  'accept': '接受',
  'accept_pass_agreement': '我接受密码丢失协议',
  'account': '帐户',
  'account_balance': '账户余额',
  'account_holder': '帐户持有人',
  'account_number': '帐号',
  'account_numbers_length_warning': '帐号必须介于 11 到 16 位数字之间',
  'account_registration': '账户注册',
  'add_card': '添加卡片',
  'add_card_info': '连接卡',
  'add_new_platform': '添加新平台',
  'address': '地址',
  'agree': '同意',
  'agree_to_the_agreement_v001': '同意协议v0.0.1',
  'agreement': '协议',
  'agreement_is_required': '需要达成协议。',
  'airdrop_success': '🎉 100,000 P2U 硬币已添加到您的钱包。',
  'airdrop_previously_received': '🚫 您之前已收到 100,000 P2U 硬币。',
  'alien_identity_verification': '外国人身份验证',
  'amount_in': '@token 中的数量',
  'amount_in_krw': '韩元金额',
  'amount_in_usdt': 'USDT金额',
  'amount_in_msq': 'MSQ 中的数量',
  'amount_not_swapped': '您的钱包中没有足够的 MATIC',
  'amount_swapped': '金额转换',
  'and_final_proceedings_11': '和最终批准决定程序',
  'announcement': '公告',
  'add_document': '添加文件',
  'add_family_document': '添加家庭关系文件',
  'app_language': '中文',
  'application_date': '申请日期',
  'apply_for_super_save': '申请 SUPER SAVE',
  'super_trust_tool_tip_content':
  'Super Trust 是一个旨在为我们的忠实用户提供福利和福利的计划。',
  'super_trust_tool_tip_label': '什么是超级信任？',
  'woohoo': '再投资超过 50% 已达到 🥳',
  'super_trust_bottom_sheet_content': '您已被认可为\n忠实会员，我们很高兴为您颁发\n超级信任徽章。',
  'apply_for_super_save_helper_service': '申请SUPER SAVE帮手服务',
  'approval_date': '批准日期',
  'approved': '得到正式认可的',
  'are_you_sure_you_want_to_cancel': '你确定要取消？',
  'participation_cancel_dialog_title': '取消参与',
  'super_save_participation_cancel_dialog_title': '您未完成参与。您确定要取消吗？',
  'complete_later': '稍后完成',
  'as_monday_1': '- 赊销付款方式，所选赊销付款 在付款期内按日分期付款，每周结算后 每周一分批付款。',
  'at_the_repayment_12':
  '交易完成的同时，卖方（人）产生信用付款应收账款（365天分期收取），MSQUARE GLOBAL Co. Ltd明白会产生债务，并清楚认识到存在风险不偿还债务的因素。正在做原则上，我们同意双方友好地讨论偿还债务过程中出现的问题。',
  'attempts_remaining': '其余的尝试',
  'available_balances': '可用余额',
  'available_token': '可用的 @token',
  'back_to_home': '返回首页',
  'back_to_home_page': '回到主页',
  'balance_certificate': '余额证明',
  'balance_certificate_img': '余额证明img',
  'balance_check': '余额查询',
  'balance_sync': 'P2U挖矿',
  'balance_sync_details_subtitle': '您的银行卡历史记录在以下日期进行过处理',
  'balance_sync_info': '从上午 00:00:00 至上次采矿时间的扫描周期。',
  'balance_sync_date': '@start_date 至 @end_date',
  'balance_sync_last_updated': '上次：@last_updated',
  'balance_sync_details': '余额同步详情',
  'balance_sync_not_processed_yet': '尚未处理！',
  'balance_sync_msg': '请求已排队，完成后您将收到通知。',
  'company_card': '您需要添加卡公司信息。',
  'bank': '银行',
  'bank_account': '银行账户',
  'bank_account_deleted': '银行账户已删除',
  'bank_account_not_added': '未添加银行帐户',
  'bank_account_not_deleted': '银行账户未删除',
  'bank_account_not_found': '找不到帐号。 请再检查一次。',
  'bank_choice': '银行选择',
  'bank_transfer_paypal_and_more': '银行转账、Paypal 等',
  'being_paid': '被支付',
  'card_management': '卡片管理',
  'birth_date': '出生日期',
  'boarding_screen_tagline_1': '从我们支持的商店购买任何产品并使用您的 MSQ 钱包付款',
  'boarding_screen_tagline_2': '轻松处理您所有的数字资产。 储存、转移甚至交易。',
  'boarding_screen_tagline_3': '通过我们的 MFA 授权系统，您可以控制您的交易和资产管理',
  'boarding_screen_tagline_4': '赚取积分并将其用作我们附属商店的现金返还',
  'bug_report': '错误报告',
  'bug_report_msg': '您可以将您的问题或反馈意见发送给我们，以便SUPER SAVE。',
  'bug_report_title': '在使用SUPER SAVE时遇到了问题？',
  'buy_products': '采购产品',
  'byungho_choi': '崔秉浩',
  'calculation_of_amount_18': '赊销结算金额计算',
  'calculation_of_amount_18_usdt': '赊销结算金额计算（USDT买入@token+存入@token）',
  'calculation_of_amount_tooltip': '（USDT购买@token + 充值@token）',
  'calculation_of_payable_21': '应付账款每日等额支付的计算',
  'camera_rotation': '相机旋转',
  'cancel': '取消',
  'cancel_ad_creating': '取消广告创建？',
  'cancel_participation': '取消',
  'modify': '调整',
  'cancellation': '消除',
  'cancellation_is_complete': '取消完成',
  'cannot_be_canceled': '无法取消',
  'card_added': '正在检查您的银行卡信息',
  'card_company': '卡片公司',
  'card_company_cannot_be_empty': '卡公司不能为空',
  'card_not_added': '无法添加您的贺卡，请重试。',
  'card_password': '卡网站登录 PW',
  'case': '案件',
  'category': '类别',
  'change_password': '更改交易密码',
  'characters': '字符',
  'check': '查看',
  'check_balance_certificate': '检查余额证明',
  'check_super_details_10': '查看 SUPER SAVE 钱包转账详情',
  'check_minimum_Requirements': '检查最低要求',
  'children_under_save_2': '14 岁以下儿童无法使用 SUPER SAVE。',
  'choose_a_lookup_period': '选择查找期间',
  'clear_filters': '清除过滤器',
  'click_to_picture_7': '点击启动相机，将身份证放在脸下拍照。',
  'click_to_picture_8': '按下相机按钮，把身份证放在脸旁。',
  'click_to_yourself_5': '单击以激活相机并自行拍照。',
  'close': '关',
  'coin_price': '硬币价格',
  'comment': '评论',
  'currency_change': '货币变化',
  'company_registration_number': '公司注册号码',
  'add_p2u_store_photo_invalid': '需提供商店照片。',
  'add_p2u_company_document_invalid': '需要公司文件。',
  'add_p2u_store_name_invalid': '商店名称为必填项。',
  'add_p2u_store_category_invalid': '必须填写商店类别。',
  'add_p2u_store_detail_invalid': '需要商店详细信息',
  'add_p2u_store_city_invalid': '必须填写市/县。',
  'enter_company_registration_number': '输入公司注册号',
  'completed': '完全的',
  'confirm': '查看',
  'country_code': '国家代码',
  'phone_num': '电话号码',
  'usdt_conset_title': '使用该服务需要同意',
  'participation_usdt': '[必填] SUPER SAVE USDT 条款及细则',
  'registration_usdt': '[必填]身份识别服务协议条款和条件',
  'confirm_change_password_1': '确认您的身份，更改 MSQUARE MARKET 钱包密码。',
  'confirm_change_password_2': '在您登录后，您可以更改您用于交易的密码。',
  'confirm_new_password': '确认新密码',
  'confirm_pass': '确认密码',
  'confirm_payment': '确认付款',
  'confirm_traded_19': '- 确认以上信息正常交易。',
  'confirmation_date': '确认日期',
  'connect_bank_account_complete_dialog_title': '账号注册完成。',
  'connect_bank_account_complete_result_second':
  '1个工作日内\n负责人将核对注册信息\n注册完成后即可使用SUPER SAVE。',
  'connect_bank_account_subtitle': '需要支付押金和资本利得税结算。',
  'connect_bank_account_title': '请注册一个帐户。',
  'connected_platforms': '互联平台',
  'consent_to_use_of_service': '同意使用服务',
  'consent_to_use_of_service_v001': '同意使用服务 v0.0.1',
  'contact_us': '联系我们',
  'contact_us_error_1': '感谢您联系我们',
  'contact_us_error_2': '无法得到您的回应。 请重试',
  'contact_us_error_3': '主题值为空',
  'contact_us_error_4': '邮箱值为空',
  'contact_us_error_5': '消息值为空',
  'contact_us_error_6': '电子邮件无效！ 请重试',
  'contact_us_msg': '如果您有任何疑问和问题，请与我们联系。',
  'contact_us_title': '我们该怎样帮助你？',
  'copy': '复制',
  'copy_address': '复制地址',
  'copy_and_send_referral_code': '复制并向朋友发送推荐代码，获得额外优惠。点击复制或与朋友分享。',
  'create': '创造',
  'create_id': '创建用户 身份',
  'create_p2p_ad': '创建 P2P 列表',
  'create_pass': '创建钱包密码',
  'create_pass_agreement_label_1':
  'MSQUARE MARKET是一款基于区块链技术的去中心化钱包，不存储用户密码。',
  'create_pass_agreement_label_2':
  '用户自行负责密码管理，密码一旦丢失将无法找回，MSQUARE MARKET 皮夹内所有数字资产将无法访问。',
  'create_pass_agreement_label_3':
  '注意：MSQUARE 无法帮助您解决密码丢失的问题。 请花点时间将密码保存在您的记事本上。',
  'create_pass_agreement_title': '用户对密码丢失负责',
  'credit_payment_rate': '信用支付率',
  'credit_sale_amount_4':
  '赊销请求\n@deposit_token @standardcurrency 了转换金额',
  'credit_sale_amount_pm': '赊销请求\n@token @pm 转换金额',
  'credit_sale': '认股权证',
  'credit_sale_application': '赊销申请',
  'credit_sale_application_modify': '赊销申请修改',
  'super_save_application': '슈퍼세이브 신청',
  'super_save_application_modify': '슈퍼세이브 신청 수정',
  'super_save_shared_mesage':
  '我的超级省钱推荐代码是: @code 下载 MSQUARE MARKET: https://onelink.to/mq2g22',
  'super_save_shared_mesage_fb':
  '我的超级省钱推荐代码是: @code 从 Playstore/Appstore 下载 MSQUARE MARKET',
  'c_r_modify_msg': 'Y您只能更改赊销金额。',
  'c_r_modify_done': '您的修改请求已发送。',
  'c_r_modify_done_title': '收到修改请求。',
  'credit_sale_daily_equal_payment': '赊销每日等额\n付款',
  'credit_sale_msq_pairs_quantity': '信用销售@token 对数量',
  'credit_sale_total_msq_quantity': '信用销售@token 总量',
  'credit_sale_quantity_10': '赊销申请 @token 数量',
  'total_credit_sale_amount': '赊销总额  @token 金额',
  'cash_buy_total_amount': '公司保证金购买的SUT总量+直接发送的SUT',
  'total_credit_sale_amount_cr_s': '(!) 通知',
  'cash_buy_total_amount_cr_s': 'SUT存入公司现金后直接购买',
  'credit_sale_quantity_11': '赊销申请 @token 数量',
  'credit_sale_rate_12': '赊销付款付款期限（付款率）',
  'credit_sale_rate_7': '赊销付款\n付款期限（付款率）',
  'credit_sales_method_9': '赊销付款\n付款方式',
  'credit_sales_payment': '赊销付款',
  'credit_sales_payment_amount': '赊销付款金额',
  'credit_sales_payment_method': '赊销付款方式',
  'credit_sell_request_msq_quantity': '信用销售请求\n@token 数量',
  'credit_transaction_credit_6':
  '赊销交易是指订立销售合同并交付产品，但在一定期限后结算价格的交易，也称为信用交易或信用交易。这些信用交易创建了一种贷款与债务的关系，基于信用来支付未来的债务。',
  'criteria_during_participation': '参与期间的标准',
  'cumulative_payment': '累积付款',
  'cumulative_payment_1': '累计付款',
  'current_password': '当前密码',
  'current_price_1msq': '当前价格为 1@token=@standardamount@mode',
  'otc_current_price_1msq': 'OTC 当前价格 1@token=@standardamount@mode',
  'open_market_price_1msq': '公开市场当前价格 1@token=@marketamount@mode',
  'currently_unavailable': '当前不可用',
  'currency_selection': '货币选择',
  'daily_equal_payment': '每日等额支付',
  'daily_payment': '每日付款',
  'daily_payout': '每日支出',
  'date_and_time_of_foreign_sale': '国外销售的日期和时间',
  'date_and_time_of_payment': '付款日期和时间',
  'date_of_birth': '出生日期',
  'date_of_transaction': '交易日期',
  'day': '日',
  'deadline': '最后期限',
  'decline_approval': '拒绝公司批准',
  'delete_account': '删除帐户',
  'delete_store': '您确定要删除商店吗？',
  'delete_store_msg': '정보 수정을 위해 삭제하지 마세요!',
  'delete_card': '您确定要删除卡片吗？',
  'delete_platform': '您确定要删除 Platform 吗？',
  'denied': '拒绝',
  'deposit': '订金',
  'deposit_account': '存款账户',
  'device_default': '设备默认值',
  'deposit_complete': '存款完成',
  'deposit_scheduled': '预定存款',
  'details_of_my_participation_amount': '我的参与金额详情',
  'disconnect': '断开',
  'discounted_products': '打折产品',
  'done': '已完成',
  'email_address': '电子邮件地址',
  'enter_account_number': '输入账号',
  'enter_amount': '输入金额',
  'enter_card_password': '输入登录密码',
  'enter_login_id': '输入您的登录 ID',
  'enter_message': '输入留言',
  'enter_numbers_only': '仅输入数字',
  'enter_pass': '输入您的 MSQUARE MARKET 密码',
  'enter_the_transmitted_txid_value': '输入传输的TXID值',
  'enter_user_id': '为您的钱包输入用户 身份。',
  'error': '误差',
  'error_1': '错误',
  'error_404': '网页未找到',
  'error_500': '内部服务器错误',
  'error_500_msg': '流量目前非常高。',
  'error_502': '坏网关',
  'exit_app': '退出应用程序',
  'exit_app_msg': '你想退出应用程序吗？',
  'expected_payment_amount': '预计付款金额',
  'expiry_': '到期:',
  'education_notice': '通知',
  'education_add_photo': '添加照片',
  'education_credit_Sales': '信贷销售教育',
  'education_done': ' 月 完成教育！',
  'education_tooltip_message': '没有经过验证的教育，\n您就不能正确地进行赊销。',
  'education_issued_date': '发布日期',
  'education_current_period': '当前教育阶段',
  'month_schedule': ' 月日程',
  'education_next_period': '下一个教育阶段',
  'education_verify': '验证教育',
  'education_waiting_approval': '审查中',
  'education_reattach': '重新连接',
  'education_completed': '完成教育',
  'education_denied': '拒绝，再试一次',
  'education_document': '请在此处添加您的照片。',
  'add_education_document': '添加教育照片',
  'super_save': 'SUPER SAVE',
  'file_upload': '上传文件',
  'upload': '上传',
  'file_uploaded': '文件上传成功',
  'file_size_warning': '文件大小大于 10MB',
  'file_upload_waiting': '文件正在上传，请稍候',
  'fingerprint_authentication': '指纹认证',
  'fingerprint_failed': '指纹认证失败',
  'fingerprint_popup': '输入密码以启用指纹认证',
  'fingerprint_text': '使用您的指纹而不是密码来处理付款。',
  'first_must_be_lower': '第一个字符必须小写',
  'family_relationship_document': '家庭关系文件',
  'for_msq_service_15':
  '对于MSQ信用交易，您需要申请P2P交易以及使用MSQ进行信用交易，如果您想将所有手续委托给“帮手服务”，以防止因您的经验不足而可能发生的受骗、诈骗、盗窃等意外情况在方法中做。您同意不因使用帮手服务而向本公司追究任何法律责任。',
  'for_transfer_28': '- 结算后转账，每次转账均需支付费用。',
  'foreigner_registration_number': '外国人登记号码',
  'foreigners_residing_korea_5': '居住或访问韩国的外国人',
  'from': '从',
  'no_transaction_of_p2u_mining': '没有P2U挖矿交易。',
  'get_involved': '继续',
  'go_to_super_save': '转到“超级节省”',
  'go_to_credit_sale': '前往赊销',
  'great': '伟大的',
  'having_problems_with_super_save': '使用超级保存有问题吗？',
  'hello': '你好',
  'history': '历史',
  'history_list_empty': '您的历史列表为空！',
  'home': '家',
  'hong_gil_dong': '洪吉童',
  'hundred_million': '亿',
  'i_agree_content_24': '我同意 MSQ 信用销售以及所请求的内容。',
  'i_clearly_transaction_11': '我清楚地了解SUPER SAVE是一项MSQ信用交易。',
  'i_sure': '是的，我确定',
  'id_verification_verification_3': '进行身份验证时需要进行身份验证。',
  'idpassport__face_photo': '身份证/护照+正面照片',
  'idpassport_photo': '身份证/护照照片',
  'if_234_21': '- 如果随意伪造或篡改此证明，可能会根据刑法（第251条和第234条）受到处罚。',
  'if_change_23': '- 如果周一是节假日，金额将在下一个工作日支付\n不变。',
  'if_charged_43': '- 如果您参加2次或以上SUPER SAVE，则仅收取1次费用。',
  'if_you_choose_to_cancel': '如果您选择取消，您输入的详细信息将会丢失？',
  'if_you_photographed_2': '如果您在该区域内匹配您的身份证，则会自动拍照。',
  'if_you_quotes_10':
  '如果您已存入 MSQ 来申请 SUPER SAVE 参与，但因简单改变主意而要求退款，您将在 10 天内按照根据《特别金融交易法》报告和接受的兑换价格退还给 MSQ。\\ n(例) 返回MSQ = 初始申请金额 / 交易所MSQ报价',
  'image_successfully_saved_in_gallery': '圖像已成功保存在圖庫中',
  'image_upload': '图片上传',
  'id_photo_upload': '证件照上传',
  'percent': '百分比',
  'profile_photo_upload': '个人资料照片上传',
  'photo_uploaded': '照片已上传。',
  'document_uploaded': '上传的文件',
  'stores': '商店',
  'p2u_store': 'P2U商店',
  'p2u_stores_title': 'P2U商店',
  'my_p2u_store': '我的 P2U 商店@s@n@e',
  'p2u_store_business_number_txt1': '仅有业务编号是不够的。',
  'registered_p2u_store': '注册的 P2U 商店（@stores）',
  'p2u_store_near': '您附近的商店',
  'p2u_store_payment_error': '在处理您的付款时似乎出现了错误，请重试',
  'p2u_find_in_this_area': '在该区域查找',
  'p2u_quantity': 'P2U 数量',
  'p2u_krw_conversion_amount': 'P2U 韩元兑换额',
  'filters': '过滤器',
  'add_p2u_store': '添加 P2U 商店',
  'add_p2u_page_title': '注册 P2U 商店',
  'add_p2u_page_title_update': '更新 P2U 商店',
  'update_p2u_popup_title': 'P2U加盟店注册重复确认',
  'update_p2u_popup_subtitle': 'P2U加盟店にすでに存在する事業者登録番号です。',
  'p2u_store_verfied': '可以注册商业登记号码。',
  'add_p2u_first_description': '请填写商店详细信息。',
  'add_p2u_second_description': '您添加的商店对所有用户都是可见的。',
  'add_p2u_guide': ' P2U 商户注册指南',
  'add_p2u_store_photo_title': '商店照片',
  'add_p2u_store_photo': '添加照片',
  'add_p2u_store_photo_uploaded': '上传商店照片',
  'add_p2u_store_document_upload': '上传商店文件',
  'add_p2u_company_document_title': '公司文件',
  'add_p2u_company_document': '添加公司文件',
  'add_p2u_store_name_title': '商店名称',
  'add_p2u_store_name': '输入商店名称',
  'add_p2u_merchant_code_title': '商家代码',
  'add_p2u_merchant_code': '输入商家代码',
  'add_p2u_store_category_title': '商店类别',
  'add_p2u_store_category': '商店类别',
  'add_p2u_store_detail_title': '商店详细信息',
  'add_p2u_store_detail': '输入商店详细信息',
  'add_p2u_store_select_city': '选择市/县',
  'add_p2u_store_city': '市/县',
  'map_link': 'Naver 搜索链接',
  'optional': '选修的',
  'store_web_link': '输入 Naver 搜索链接',
  'invalid_map_link': '无效的 Naver 搜索链接',
  'no_store_detail': '无可用详细信息',
  'add_p2u_store_address': '输入地址',
  'add_p2u_store_address_invalid_message': '请在地址下拉菜单中选择一个地址。',
  'add_p2u_store_added_successfully': '已成功添加 P2U 商店',
  'add_p2u_store_store_added': '您之前已经添加了 P2U 商店。',
  'add_p2u_store_submit': '注册商店',
  'add_p2u_store_submit_update': '更新商店',
  'total_store': '店铺',
  'filter_p2u_store_distance_input_label': '距离（公里）',
  'filter_p2u_store_distance_input_label2': '公里半径',
  'all_store': '所有商店',
  'all_store_in_location': '@x KM 的商店',
  'all_store_in_city': '商店 @city',
  'in': '在',
  'in_progress': '进行中',
  'incorrect_password': '不正确的密码',
  'index__1_month': '@index个月',
  'information_on_participation_11': '有关可能参与的信息',
  'input_cannot_be_empty': '输入不能为空。',
  'internet_restored': '互联网回来了',
  'invalid_password': '无效的密码',
  'invalid_token_type': '无效的令牌类型',
  'invoices_to_this_mail': '发票将发送到此电子邮件',
  'it_means_deadline_8':
  '意味着用户将产生信用交易付款的应收账款，MSQUARE总公司将产生债务，双方同意在约定的付款期限内完成付款。',
  'koreans_aged_14_and_over': '14岁以上韩国人',
  'krw': '韩元',
  'last': '最后',
  'last_7_digits': '最后 7 位数字',
  'learn_more': '了解更多',
  'let_go': '松手',
  'listing_type': '列表类型',
  'login_id': '卡网站登录 ID',
  'logout': '登出',
  'logout_msg': '返回将注销当前用户',
  'm_square_global_co_ltd': '超级信托公司',
  'm_square_market': 'MSQUARE MARKET',
  'main_account': '主账户',
  'main_account_cannot_deleted': '主帐户无法删除。解决方案： 添加替代账户并更改主账户，然后删除当前账户。',
  'main_bank_account_changed': '主要银行账户已更改',
  'main_bank_account_not_changed': '主要银行账户未更改',
  'match_your_photographed_3': '将您的脸部和身份证件与该区域匹配\n系统将自动拍照。',
  'make_a_payment': '付款',
  'max': '马克斯',
  'message': '讯息',
  'msq_market_selling_11': '赊销前 MSQ 市值',
  'msq_price_sale_17': '赊销时的 @token 价格',
  'msq_transmission_date': '@token（转账日期 @date）',
  'msq_wallet_address': '@curr 钱包地址',
  'must_include_special': '必须包含特殊字符和数字',
  'must_include_upper_lower': '必须包含大写和小写字母',
  'mutual_confidentiality_problem_13':
  '对于本次 MSQ 信用交易的事实（包括细节），以及未经事先同意而通知他人或其他公司的行为，通知互联网社区、公告板、我同意违规方对该问题承担无限的民事和刑事法律责任。',
  'mute_push_notifications': '推送通知静音',
  'mute_notifications': '静音通知',
  'my_account': '我的帐户',
  'my_bank_accounts_note1.': '交易在注册为主账户的账户中执行。',
  'my_contribution': '我的贡献',
  'my_daily_equal_payout': '我的每日等额支付',
  'my_points': '我持有的 P2U',
  'my_remaining_balance': '我的余额',
  'my_wallet': '我的钱包',
  'mobile_phn_verification': '手机验证',
  'n_week_of_month': '每月第@w周',
  'name': '姓名',
  'name_of_bank': '银行名称',
  'no_companies': '没有公司',
  'no_bank_account': '您需要添加一个银行账户才能完成超级储蓄的参与',
  'no_usdt_wallet': '您需要添加一个钱包才能完成超级省钱活动',
  'national_identity_verification': '国民身份验证',
  'nationality': '国籍',
  'nationality_selection': '国籍选择',
  'nearest': '最近的',
  'new_notification': '新通知',
  'new_member_only_can_add_referral': '仅限新会员添加推荐人。',
  'new_password': '新密码',
  'newest': '最新',
  'news': '消息',
  'next': '下一个',
  'no_card': '⚠️ 照片中未检测到卡片。您想继续使用此图像吗？',
  'no_card_added': '未添加卡片',
  'no': '不',
  'no_file_selected': '未选择文件',
  'no_internet_connection': '没有网络连接',
  'no_news': '没消息',
  'no_permission': '无权限',
  'no_permission_permanent': '权限永久被拒绝，请前往设置并允许。',
  'no_platform_added': '未添加平台',
  'no_record_found': '没有找到记录',
  'no_registered_accounts': '没有注册帐户。',
  'no_result': '没有搜索结果',
  'no_tokens': '没有代币',
  'not_enough_balance': '不充足的资金',
  'not_enough_msq': '您钱包中的 MSQ 不足',
  'not_enough_msqp': '您钱包中的 MSQP 不足',
  'not_enough_p2up': '您钱包中的 P2UP 不足',
  'not_enough_tokens': '您钱包中的 @token 不足',
  'nothing_to_show': '没有什么可展示的',
  'notification_supersave_payout_approved': '您的 SUPER SAVE 结算请求已获批准.',
  'notification_supersave_title_approved': '您的 SUPER SAVE 参与请求已获批准.',
  'notification_supersave_title_declined': '您的 SUPER SAVE 参与请求已被拒绝.',
  'notifications': '通知',
  'notifications_for_settings': '通知',
  'notification_credit_success': '您收到了新的信用销售权。不要忘记完成参与。',
  'notifications_sound': '通知声音',
  'notification_setting': '通知设置',
  'notification_super_save': '超级节省',
  'notification_device_default': '设备默认值',
  'notification_credit_failed': '赊销交易失败。',
  'notifications_from': '来自',
  'notifications_to': '至',
  'np_cp_not_match': '新密码和确认密码不匹配',
  'same_cp_np': '新密码不能与当前密码相同',
  'null_value': '值不能为空',
  'number_of_people': '人数',
  'ok': '好的',
  'okay': '好的',
  'btn_check': '检查',
  'we_r_sorry': '我们很抱歉！',
  'req_not_fulfil': '您不符合超级信托 NFT 的最低要求！',
  'nft_available': '可用的 NFT 福利',
  'nft_not_available': '不提供 NFT 福利',
  'nft_benefits_lost': 'NFT 利益损失',
  'nft_requirements': 'NFT 要求',
  'nft_requirements_txt1': '最低要求',
  'nft_requirements_txt2': '以下是您需要满足的享受超级信托福利的最低要求。',
  'nft_requirements_txt3': '超级储蓄计划每周结算金额50%或以上的返还参与者会员资格。',
  'nft_paused': '您不再拥有超级信托 NFT 权利。',
  'nft_paused_det': '由于未达到最低要求，您失去了超级信托 NFT 福利。',
  'one_two_bank_11011234': '一二银行1101*****1234',
  'or': '或',
  'on': '关于',
  'off': '关闭',
  'order_cannot_be_deleted': '订单无法删除',
  'order_completed': '订单完成',
  'order_not_placed': '您的订单无法下达。 请再试一遍',
  'order_successfully_deleted': '订单已成功删除',
  'our_products': 'MSQUARE 平台 / SNS',
  'other': '其他',
  'out': '出去',
  'p2p_listings': '我的 P2P 列表',
  'p2p_listings_empty': 'P2P 列表为空',
  'p2p_trade': 'P2P 交易',
  'p2p_trading': 'P2P 贸易',
  'p2p_trading_msg': '交易您的数字资产',
  'paid_out': '支付',
  'paid_with': '付款方式',
  'participant_num': '参与情况 共 @n 例',
  'participate_in_super_save': '参加超级省钱活动',
  'participation_complete': '查看待处理/已批准列表',
  'applied_lists': '申请列表',
  'applied_list_empty': '您申请的列表是空的！',
  'pass': '口令',
  'pass_change_fail': '密码未更改',
  'pass_change_success': '密码更换成功',
  'pass_limit_reached': '已达到密码尝试次数上限。 5 分钟后重试',
  'pass_not_match': '密码不符',
  'pass_verify': '密码校验',
  'payment_amount': '支付金额',
  'payment_completed_amount': '付款完成金额',
  'payment_details': '付款详情',
  'get_card_management': '获取卡管理',
  'payment_mondays_11': '- 付款期间按日分期付款，每周一付款。',
  'payment_status_by_case': '按参与案例付款情况 共 @n 例',
  'permissible_to_sale_2': '允许申请对外销售',
  'phone_number': '电话号码',
  'place_your_card_5': '将身份证放在脸部左侧或右侧\n，根据区域拍照。\n注意不要将光线反射到您的身份证上\n。',
  'platform': '平台',
  'please_add_family_relationship_document': '请在此处添加您的家庭关系文件。',
  'please_check_complete_3': '申请完成后不可修改，请仔细核对。',
  'please_check_information_2': '请检查申请信息。',
  'please_enter_application_2': '请输入赊销申请所需的信息。',
  'please_enter_information_2': '请输入申请人信息。',
  'please_enter_number_2': '请输入您的居民登记号码。',
  'please_enter_phone': '请输入您的手机号码。',
  'please_enter_payment_information': '请输入付款信息。',
  'please_enter_valid_amount': '请输入有效金额',
  'please_enter_6_digit': '请输入六位验证码。',
  'please_note': '请注意',
  'please_note_1': '请注意。',
  'please_note_approval_5':
  '请注意，申请超级节省后，可能会因总公司的情况而被拒绝批准。 Supersave 申请（MSQ 信用交易申请）不保证 Supersave 批准（MSQ 信用交易批准）。',
  'please_prepare_your_id': '请准备好您的身份证件。',
  'please_read_agree_2': '请阅读以下信息并输入“我同意”。',
  'please_read_agree_22': '请阅读以下信息并输入“我同意”。',
  'please_register_clear_3': '\n请检查您的身份证上的字母是否清晰后再进行注册。',
  'please_register_clear_4': '请检查您的脸部和身份证件上的字母是否清晰后再进行注册\n。',
  'please_send_sale_3': '请发送\n您已申请赊销的 MSQ。',
  'please_send_save_3': '请将有关 SUPER SAVE 的任何问题或反馈发送给我们。',
  'please_set_id_4': '请将其设置在 \n 区域内，以免光线反射到 ID 上。',
  'pls_create_pass': '请创建交易密码。',
  'possibility_to_participate': '参与的可能性',
  'possible_to_participate': '可以参加',
  'price_integration': '价格整合',
  'privacy_policy': '隐私政策',
  'privacy_settings': '隐私设置',
  'open_setting': '設定を開く',
  'proceed_transaction': '您要继续进行此交易吗？',
  'proceed_wallet_termination': '为了继续终止钱包，请在下面输入密码',
  'really_sure': '您确定要继续进行交易吗',
  'recipient': '接受者',
  'recommended': '推荐',
  'refresh': '刷新',
  'refresh_balance': '刷新余额',
  'refuse': '拒绝',
  'reserved_cash': '(预留现金)',
  'register_bank_account': '注册银行账户',
  'change_bank_account': '更改银行账户',
  'change_bank_account_req': '更改银行账户请求。',
  'has_pending_req': '您已经有待处理的变更请求。',
  'registration': '登记',
  'registration_date': '注册日期',
  'registration_number_digits_7': '注册号必须为 7 位数字。',
  'representative_name': '代表姓名',
  'request_confirmation': '注册完成',
  'request_confirmation_msg': '钱包地址已创建。',
  'request_for_address_and_balance': '要求提供地址和余额',
  'request_for_krw_10': '请求赊销 @token @standardcurrency 兑换金额',
  'request_for_krw_3': '请求赊销 @token @mode 兑换金额',
  'transfer_krw': '购买价格\t发送。',
  'transfer_token': '发送 。',
  'transfer_credit_sale_right_title': '转让应收账款',
  'transfer_credit_sale_right_txt1': '转至',
  'transfer_credit_sale_right_txt2': ' 您同意转让赊销权吗？',
  'settlement_amount': '赊销金额\t得到正式认可的。',
  'request_for_krw_ss': '赊销审批请求金额',
  'request_for_krw_cs': '使用赊销权（国外销售权）',
  'won_cs': '元元',
  'referral': '推荐',
  'referral_code_social': '推荐代码',
  'requested_by': '请求人',
  'requested_help': '请求帮助',
  'requested_msq_minutes_7': '10 分钟内请求 SUT 数量',
  'reserve_reserve_consumption_rate': '准备金消耗率',
  'reserves': '储备',
  'reset': '重置',
  'resident_registration_number': '居民登记号码',
  'resolve_errors': '请修正错误',
  'retry': '重试',
  'Register_a_supersave_transaction': '注册超级省钱交易',
  'save_transaction_confirmation': '保存交易确认',
  'scan_finger': '扫描手指继续',
  'scan_finger_to_connect': '扫描您的指纹以确认交易',
  'scan_qr_code': 'Scan QR Code',
  'secure_layer': '安全层',
  'see_details': '查看更多',
  'see_more': '查看具体信息',
  'see_exam': '例子',
  'review': '审查',
  'add_cash_transfer': '添加现金转账截图',
  'add_coin_transfer': '添加代币转账截图',
  'add_more': '+ 添加更多',
  'cash_trans_sample': '现金转账样本',
  'coin_trans_sample': '硬币转账样本',
  'recommend_to': '赊销权申请人（国外销售权持有者）',
  'recommend_to_be': '您介绍的人',
  'apply_ss': '超级节省申请',
  'apply_credit_sale': '赊销申请',
  'super_save_user': '超级节省用户',
  'credit_sale_user': '赊销用户',
  'application_type': '应用类型',
  'review_attachment': '审查附件',
  'txid_error': '这是一个已经注册的 TXID。',
  'err_trans_cap': '请附上两份转账截图。',
  'err_txid': '请验证您的交易TXID',
  'tx_id_fine': '这是一个普通的 TXID。',
  'unable_to_upload': '无法上传截图。',
  'select_an_accounts_13': '选择账户进行支付',
  'select_bank': '选择银行',
  'select_identity_verification_type': '选择身份验证类型',
  'select_your_card': '选择您的卡',
  'send': '发送',
  'sender': '发件人',
  'sensitive_information_act_3': '根据个人信息保护法对敏感信息进行加密和安全保护。',
  'sent_date': '(发送日期@date)',
  'sent_successfully': '发送成功。',
  'service_withdrawal': '退出服务',
  'service_withdrawal_apply': '申请提款',
  'service_withdrawal_complete_dialog_title': '您的取款请求已完成，\n您将被注销。',
  'service_withdrawal_deposit_into_account': '余额将存入您的注册账户。',
  'service_withdrawal_input_hint': '输入原因',
  'service_withdrawal_irreversible': '退出申请不可撤回，请慎重决定。',
  'service_withdrawal_reason_1': '不想再使用该应用程序',
  'service_withdrawal_reason_2': '错误导致使用不便',
  'service_withdrawal_reason_3': '应用程序很难使用',
  'service_withdrawal_reason_4': '直接输入',
  'service_withdrawal_reason_title': '请输入您离开我们的原因',
  'service_withdrawal_rules_1': '如果您取消服务，所有个人信息将被销毁。',
  'service_withdrawal_rules_2': '其他强制存储的信息按照相关法律法规的规定单独存储并在一定期限内销毁。',
  'service_withdrawal_rules_3': '重新注册后，会员信息和账户信息不会自动恢复。',
  'service_withdrawal_rules_4a': '退出请求在工作日 24 小时内处理，',
  'service_withdrawal_rules_4b': '退出后 6 个月内无法重新注册。',
  'service_withdrawal_rules_5a': '申请退会时，',
  'service_withdrawal_rules_5b': '您将被注销，',
  'service_withdrawal_rules_5c': '您将无法登录，',
  'service_withdrawal_rules_5d': '无法使用所有服务。',
  'service_withdrawal_rules_title': '请在离开我们之前检查',
  'set_as_main_account': '设为主账户',
  'settings': '设置',
  'sound': '声音',
  'super_save_approval_rejection': '超级保存批准/拒绝',
  'super_save_daily_payouts': '超级省钱每日支付',
  'p2u_auto_mining_results': 'P2U 自动采矿成果',
  'date': '日期',
  'date_': '日期:',
  'settlement_date': '结算日期',
  'settlement_date_1': '（结算日）',
  'shall_we_on_2': '从现在开始我们要参加SUPER SAVE吗？',
  'shall_we_sale_20': '我们从现在开始参加SUPER SAVE吗？\n申请赊销后10分钟内即可参加\n。',
  'shooting_number': '射击 @number',
  'six_digit': '6位数字',
  'sign_in_with': '登陆使用',
  'sign_in_with_apple': '与苹果签约',
  'sign_in_with_facebook': '使用 Facebook 签名',
  'sign_in_with_google': '用谷歌签名',
  'sort_by': '排序方式',
  'subject': '主题',
  'success': '成功',
  'sorry': '对不起',
  'successful': '成功的',
  'super_save_act_9': 'SUPER SAVE 不是可以受《资本市场法》或《金融消费者保护法》保护的金融产品。',
  'super_save_charge_1': '经负责人确认后即可使用SUPER SAVE。',
  'super_save_charge_13': '经负责人确认后即可使用SUPER SAVE。',
  'super_save_corpo_reg_title': 'SUPER SAVE 公司交易登记',
  'super_save_corpo_business_license_header': '营业执照',
  'super_save_corpo_business_license_subtitle': '请登记您的营业执照号码和证书',
  'ss_corp_acc_change': '请输入银行帐户详细信息以更改银行帐户。',
  'super_save_corpo_name': '公司名称',
  'super_save_corpo_name_hint': '输入公司名称',
  'super_save_corpo_business_license_number': '营业执照号码',
  'super_save_corpo_business_license_number_hint': '只输入数字',
  'super_save_corpo_business_license_cert': '营业执照证书',
  'super_save_corpo_business_license_cert_hint': '选择文件',
  'super_save_corpo_account_header': '请注册一个公司账户。',
  'super_save_corpo_account_header_subtitle': '您需要用它来存入款项和结算资本利得税。',
  'super_save_corpo_account': '选择银行',
  'super_save_corpo_account_number': '输入账号',
  'super_save_corpo_account_number_hint': '只输入数字',
  'super_save_corpo_account_bank_book': '公司存折副本',
  'super_save_corpo_account_bank_hint': '选择文件',
  'super_save_day_12': '超级优惠已结束。每天10:00至16:00均可申请。',
  'super_save_ended': '超级优惠已结束。每天@start至@end均可申请。',
  'super_save_information_1': 'SUPER SAVE交易登记信息',
  'super_save_is_a_credit_transaction': 'Super Save 是一种信用交易。',
  'super_save_iscomplete_18': 'SUPER SAVE 参与\n已完成。',
  'super_save_iscomplete_19': 'SUPER SAVE 参与\n已完成。',
  'credit_sale_iscomplete_18': '赊销申请\n已完成.',
  'super_save_payment_details': 'SUPER SAVE 付款详情',
  'super_save_transaction_registration': 'SUPER SAVE 交易登记',
  'supersave_corporate_transaction_1': '交易注册完成后，注册信息将更新到您\n的个人资料中、',
  'supersave_corporate_transaction_2': '经代表确认后可享受 SUPER SAVE 优惠',
  'supersave_corporate_transaction_3': '第一次。',
  'supersave_corporate_transaction_registration_info':
  'SUPER SAVE 公司交易注册指南',
  'super_save_only_requires':
  '- SUPER SAVE 仅要求首次进行交易注册，之后的交易无需注册。\n的约定。',
  'super_save_user_guide': 'SUPER SAVE 用户指南',
  'super_save_referral_code': 'SUPER SAVE推荐代码',
  'super_save_when_registration_transaction':
  '超级节省 在登记公司交易时，需要商业登记证和公司 账户登记。',
  'super_save_corporate_reg': 'SUPER SAVE 企业交易登记',
  'super_save_corporate_contact_info': '公司交易联系方式',
  'super_save_corporate_contact_info_sub': '请正确登记负责人信息。',
  'super_save_corporate_contact_name_label': '联系人姓名',
  'super_save_corporate_contact_name_hint_text': '姓名',
  'super_save_corporate_contact_person_in_charge_label': '联系负责人',
  'super_save_corporate_contact_person_in_charge_hint_text': '只能输入数字',
  'super_save_corporate_identity_verification_cta_label': '身份验证',
  'super_save_corporate_contact_email_label': '联系人电子邮件',
  'super_save_corporate_contact_email_hint_text': '输入电子邮件',
  'super_save_corporate_contact_email_cta_label': '电子邮件验证',
  'super_save_corporate_next_cta_label': '次へ',
  'super_save_corporate_success_title': '公司交易注册完成。',
  'super_save_corporate_success_subtitle':
  '负责人将在1个工作日内验证已注册信息，注册完成后即可使用SUPER SAVE。',
  'swap': '掉换',
  'swap_token': '交换令牌',
  'swipe_left_to_next_page': '向左滑动进入下一页',
  'take_again': '再拿一次',
  'take_me_to_listings': '带我去清单',
  'take_pictures': '拍照',
  'ten_k': '仅有的',
  'terms_and_conditions': '条款和条件',
  'the_account_application_4':
  'SUPER SAVE 国外交易的购买价格将大幅提高，反映出 SUT 当前和未来的价值。',
  'the_account_use_3':
  'SUPER SAVE旨在增加MSQUARE实体经济平台生态系统的全球用户群，并扩大SUT作为支付方式的现实世界固定购买税。',
  'the_account_use_4':
  'SUPER SAVE 是一个令人兴奋的平台，它将加速 MSQUARE 实体经济平台的用户增长，使其步入陡峭的上升曲线。',
  'the_application_exceeded_5': '已超出申请限制。',
  'the_change_7':
  '- 赊销付款方式为所选赊销付款期内按日分期付款，每周一结算后分批付款。 \n - 如果周一是假期，则将在下一个工作日支付金额，\n不变。',
  'the_credit_completed_1': '赊销请求已\n完成。',
  'the_credit_completed_19': '赊销请求\n已完成。',
  'msquare_team': 'MSQUARE\n自有开发团队',
  'msquare_team_1': 'Must Fintech 是一家多平台开发公司，负责监督 MSQUARE 实体经济平台的开发。',
  'msquare_team_2': '转到必须团队 YouTube',
  'ss_inquiry': '国家超级储蓄银行联系方式',
  'the_message_value_is_empty': '消息值为空。',
  'the_number_krw_1': '我已经是注册的SUPER SAVE交易会员。',
  'the_number_processed_38': '我是已申请提现的会员，提现过程中您无法使用该服务。',
  'the_participation_day_12': '参与限额每天更新，并通过每天支付的每日等额支付恢复限额。',
  'the_payment_period_2': '付款方式是在付款期间按日分期付款。',
  'the_slips_20': '- 交易确认凭证是为了方便客户而提供，不能作为现金收据或销售单据等证据。',
  'there_are_no_search_results': '没有搜索结果。',
  'there_is_complete_2': '有一个信用销售申请可以参与SUPER SAVE。请参加后再次申请',
  'there_is_complete_20': '有一个信用销售申请可以参与SUPER SAVE。请参加后再次申请',
  'to': '至',
  'get_email_code': '获取电子邮件代码',
  'get_phone_code': '获取手机密码',
  'usdt_code_timout_title': '输入验证码超时。',
  'usdt_code_wrong_title': '验证码不匹配',
  'usdt_code_timout_msg': '您想再次收到@thing吗？',
  'text_msg': '短信',
  'call': '音频通话',
  'usdt_code_wrong_msg': '请再次检查您的验证码。',
  'usdt-resend-title': '请在再次发短信之前检查一下',
  'usdt-recall-title': '请在再次致电前检查一下',
  'usdt_sms_resend_txt': '检查您的手机号码,请确保您的手机号码输入正确;'
      '检查垃圾邮件,请检查邮件是否被归类为垃圾邮件;'
      '检查运营商,请检查该运营商是否可以接收短信。\n（服务提供商屏蔽服务、支付状态等）',
  'usdt_voice_recall_txt': '检查您的电话号码,请确保您的电话号码输入正确;'
      '检查垃圾邮件,请检查邮件是否被归类为垃圾邮件;'
      '检查您的移动运营商并确保它是可以接收语音呼叫的移动运营商。\n（服务提供商屏蔽服务、支付状态等）',
  'email_sms_resend_txt': '检查您的电话号码/电子邮件，请确保您的电话号码/电子邮件输入正确。;'
      '检查垃圾邮件请检查邮件是否被归类为垃圾邮件。;'
      '检查运营商,请检查该运营商是否可以接收短信。\n（服务提供商屏蔽服务、支付状态等）',
  'usdt_registration_txt': '使用SUPER SAVE USDT时，需要手机认证，防止他人窃取信息。\n'
      '仅首次使用SUPER SAVE USDT时需要进行交易注册，下次参与时将不再需要注册。\n'
      '交易登记完成后，会员信息中更新登记信息，经负责人确认后即可使用SUPER SAVE。',
  'usdt_regist_title': 'SUPER SAVE USDT交易注册信息',
  'usdt_regist': '注册USDT超级省钱',
  'usdt_regist_btn': 'SUPER SAVE USDT 交易登记',
  'usdt_regist_cmplt': 'USDT交易注册完成。',
  'token_transfer': '代币转账',
  'topup_credit': '充值/信用',
  'total': '总计：@length',
  'total_krw_usdt': '合计：韩元+USDT',
  'total_amount': '总金额',
  't_total_amount': '合计金额',
  'total_credit_amount_1': '赊销结算总额',
  'total_daily_equal_payout': '每日等额支付总额',
  'show_completed_participations': '显示已拒绝/已完成',
  'total_n_cases': '共 @n 例',
  'total_paid_accounts_payable': '已付应付账款总额',
  'total_participants': '参加总人数',
  'total_participation_amount': '总参与金额',
  'total_participation_history': '总参与历史记录',
  'total_remaining_accounts_payable': '剩余应付账款总额',
  'total_value': '总价值',
  'trade_registration': '贸易登记',
  'trading': '贸易',
  'transaction_confirm_msg': '您的交易已成功接受',
  'transaction_confirmation': '交易确认',
  'transaction_confirmed': '交易确认',
  'transaction_detail': '交易详情',
  'transaction_done': '交易已经完成。 请使用另一个二维码。',
  'transaction_failed': '交易失败',
  'transaction_history': '交易历史',
  'transaction_information': '交易信息',
  'transaction_name': '交易名称',
  'transaction_number': '交易号',
  'transaction_registration_participation_3':
  '仅首次使用SUPER SAVE时需要进行交易登记，下次参与时将不再需要进行交易登记。',
  'transaction_request': '交易请求',
  'transaction_type': '交易类型',
  'transaction_timeout': '交易超时，请重试。',
  'transaction_unsuccessful': '交易不成功',
  'transfer': '转让转售权',
  'transfer_to_super_save_wallet': '转账至 SUPER SAVE 钱包',
  'transmission_quantity': '传输数量',
  'try_again_later': '请稍后再试',
  'try_again_msg_1': '再试一次 中',
  'try_again_msg_2': '分钟数',
  'tx_id_cannot_be_blank': 'TX ID 不能为空。',
  'enter_valid_tx_id': '有効な TXID を入力する必要があります。',
  'txid_input_again_1': 'TXID 输入超时。请再试一次。',
  'unlock_wallet': '确认你的身份',
  'update_billing_details': '更新您的帐单详细信息和地址',
  'update_password': '更新密码',
  'update_payment_method': '连接卡',
  'usdt': 'USDT',
  'use_password': '使用密码',
  'user': '用户',
  'user_': '用户:',
  'user_details': '用户详情',
  'user_guide': '用户指南',
  'user_id': '用户身份',
  'user_name': '用户名',
  'username_copied': '用户名已复制到剪贴板',
  'email_copied': '电子邮件已复制到剪贴板',
  'address_copied': '地址已复制到剪贴板',
  'check_store_info': '查看商店信息',
  'user_id_copied': '用户 ID 已复制到剪贴板',
  'view_all': '查看全部',
  'waiting_for_approval': '等待批准',
  'wallet': '钱包',
  'wallet_type': '钱包类型',
  'wallet_id': '钱包地址',
  'wallet_address': '钱包地址',
  'wallet_id_copied': '钱包地址已被复制到剪贴板',
  'wallet_id_copied_to_clipboard': '钱包地址已被复制到剪贴板',
  'wallet_request': '钱包请求',
  'wallet_connection_request': '钱包连接请求',
  'wallet_successfully_terminated': '钱包成功终止',
  'wallet_termination': '钱包终止',
  'wallet_cannot_termination': '您不能因为拥有 SUPER SAVE 注册而终止钱包。',
  'wallet_termination_failed': '钱包终止失败',
  'wallet_termination_screen': '钱包终止',
  'want_to_logout': '是否要注销',
  'sec_threat': '安全威胁',
  'we_detected_sec_rel': '我们检测到安全威胁，暂时不允许您使用应用程序，请尝试解决此问题并重新启动应用程序。',
  'case_code': '案例代码：@c',
  'we_are_again_29': '我们无法收到您的回复。请再试一次。',
  'weekly_settlement_monday_3': '每周结算每周一进行并支付。',
  'welcome': '欢迎',
  'welcome_back': '欢迎回来！',
  'what_is_super_save': '什么是 SUPER SAVE？',
  'when_msq_voluntary_7':
  '当MSQ转移到SUPER SAVE Wallet时，交易完成，所有权转移到MSQUARE总部，所有权行使也是自愿的。',
  'when_transaction_charge_4':
  '交易登记完成后，会员信息中更新登记信息，经负责人确认后即可使用SUPER SAVE。',
  'when_using_tax_2':
  '使用SUPER SAVE时，需要进行身份验证和账户注册，以防止他人窃取信息、存款支付、结算资本利得税。',
  'When_using_supersave':
  '- 使用 SUPER SAVE 时，防止他人窃取您的信息和存款、\n支付存款和资本利得税结算等。\n需要注册账户。',
  'withdraw': '提取',
  'won': '韩元',
  'won_suffix': '韩元',
  'wrong_password': '您输入的密码错误',
  'year': '年',
  'yes': '是的',
  'you_agree_etc_14': '您同意信用付款可以现金或等值物品（黄金、大米、硬币等）支付。',
  'you_can_apply_from_1_million_krw': '您可以从@from 开始申请',
  'you_can_have_a_look_at_your_ad’s_on_your_listings_page':
  '您可以在列表页面上查看您的广告',
  'you_can_krw_6': '申请可以 @of 为单位。',
  'you_have_created_an_ad': '您制作了一个广告',
  'you_have_no_cumulative_balance': '您没有累计余额。',
  'you_sure': '你确定吗？',
  'your_order_has_been_placed': '您的订单已下达',
  'add_p2u_store_info': '您也可以点击地图进行选择。',
  'dob': '出生日期',
  'phone_company': '公司',
  'input_number_error': '输入不能为空',
  'otp_error': '验证码必须为 6 位数字',
  'offshore_labor_projects': '离岸人员配置项目',
  'wait_for_release': '等待释放',
  'resend': '重发',
  'recall': '记起',
  'call_me': '给我打电话',
  'sms_me': '改为发短信给我',
  'sms_sent': '您很快就会收到一条短信。',
  'call_sent': '您很快就会接到电话。',
  'sensitive_information_prompt': '根据个人信息保护法对敏感信息进行加密和安全保护。',
  'select_phone_company': '选择电话公司',
  'enter_phone_number': '输入电话号码',
  'enter_date_birth': '输入出生日期',
  'enter_detail': '输入您的信息',
  'input_field_error': '输入字段不能为空',
  'name_error': '名称不能为空',
  'dob_error': '出生日期不能为空',
  'number_error': '号码不能为空',
  'check_phone_number': '检查您的电话号码',
  'check_phone_number_sub_text': '请确保输入您的手机号码',
  'check_spam': '检查垃圾邮件',
  'check_spam_sub_text': '请检查该邮件是否被归类为垃圾邮件',
  'check_carrier': '检查运营商是否能够接收短信',
  'check_before_resend': '请在再次发短信之前检查一下',
  'enter_verification_code': '输入验证码',
  'verification_failure': '验证失败',
  'input_field_validation_error': '输入验证失败',
  'verification_code_error': '验证码不匹配。',
  'verification_code_error_description': '请再次检查验证码。',
  'register_param_incorrect': '您提供的一些信息不正确，请再次检查。',
  'add_referral': '谁介绍您加入超级省钱（可选)',
  'add_referral_required': '谁介绍您加入超级省钱（必填）',
  'add_referral_is_required': '推荐代码为必填项。',
  'referral_code': '超级节省',
  'referral_code_sub_title': '添加您介绍给我的人',
  'type_your_referral_code': '请输入介绍给我“超级节省”的人的代码。',
  'referral_code_error': '无效代码，它必须是5位数字',
  'referral_code_api_error': '无效的代码',
  'referral_phone_api_error': '电话号码无效，请重新检查',
  'referred_by': '推荐人:',
  'add': '添加',
  'please_confirm': '请确认',
  'grant': '授权',
  'approve_failure': '审批失败',
  'referral_code_title': '推荐码',
  'added_successfully': '添加成功',
  'add_percentage': '添加百分比',
  'how_much_percentage': '你会给多少',
  'confirmation_text': '@name将正确处理信用销售。一旦做出决定，就不能更改或撤销。你确定吗？',
  'dont_show_again': '再び表示しない',
  'referrals_not_zero': '推荐不能为零百分比。',
  'total_percentage_should_be_100': '总百分比应等于 100',
  'search_by_phone_number': '通过电话号码搜索',
  'select_transfer_percentage': '输入要转让的权利数量',
  'remained_amount_after_transfer': '转让后您剩余的权利金额。',
  'phone_code': '电话',
  'invalid_phone_code': '无效！号码不正确',
  'code_tab': '代码',
  'deny': '否定',
  'code_already_exists': '推荐码已存在',
  'invalid_registration_number': '无效的居民登记号码',
  'invalid_name': '提供的姓名无效',
  'invalid_number': '输入的号码无效',
  'card_duplicate': '您已经添加了 @index 信用卡公司，无需再添加。如果要添加其他信用卡公司，请按按钮。',
  'credit_sale_right': '您尚未使用賒銷權。(%credit_sale%)',
  'congratulations': '祝贺！',
  'go_to_credit_sale_right': '内容を確認する',
  'go_to_check': '前往检查',
  'move_to_check': '移动到检查',
  'super_saver_need_to_complete': ' 需要完成。',
  'waiting_for_response': '等待回复',
  'active_inquiry': '活跃查询',
  'solved': '已解决',
  'hold_status': '持有',
  'search_for_inquiry': '寻找查询',
  '1:1inquiry': '1对1的询问',
  'Hold': '持有',
  'by_status': '按状态',
  'by_category': '按类别',
  'status': '状态:',
  'p2p_mining_inquiry': 'P2U挖矿咨询',
  'select_category': '选择类别',
  'attachment': '附件',
  'browse_file': '浏览文件',
  'create_new_inquiry': '创建新查询',
  'message_here': '在此输入消息',
  'general': '一般',
  'bug': '错误',
  'p2u': 'P2U',
  'p2umining': 'P2U挖矿',
  '1:1inquiry_received': '收到1对1的询问',
  'inquiry_dialog_response': '感谢您提交您的咨询。我们将审核您的情况，并在接下来的24-48小时内回复您。',
  'inquiry_track_detail': ' 您可以从1:1咨询屏幕跟踪您的咨询。',
  'track_inquiry': '追踪咨询',
  'inquiry_anouncement': '您收到了一对一查询的回复.',
  'inquiry_empty': '未找到最近的查询',
  'title': '标题',
  'inquiry_created_successfully': '询问成功创建',
  'subject_error': ' 标题不能为空',
  'category_error': '类别不能为空',
  'content_field_error': '消息不能为空',
  'something_went_wrong': '出了点问题',
  'Active': '活跃',
  'Solved': ' 已解决',
  'Waiting': '等待中',
  'General': '一般的',
  'Bug': '错误',
  'SUPER SAVE': 'SUPER SAVE',
  'P2U': 'P2U',
  'P2U Mining': 'P2U挖矿',
  'super_save_is_confirmed': '%super_save_popup%已確認。',
  'super_save_popup': '超级节省',
  'credit_sale_right_created': '賒銷權\n已設立。',
  'super_save_awaits_completion': '超級儲存等待完成。',
  'commitment_document': '附上承诺文件',
  'please_add_commitment_document': '请点击下方按钮添加承诺文件',
  'add_commitment_document': '在此添加承诺文件。',
  'your_card_will_be_deleted':
  '解决方案: 根據卡片公司政策，您的卡片註冊將被刪除。 前往您的發卡公司並更改您的密碼。 確保密碼複雜。',
  'your_added_card_deleted': '您新增的卡片已刪除，需要重新新增。',
  'confirmation_letter': '确认函',
  'read_the_content': '阅读以下内容',
  'confirmation_terms':
  '当我自己或我的家人注册新的超级储蓄账户时，如果介绍人（债权人）不是家庭成员，我同意将超过50%的外部介绍权分配给外部介绍人。 如有违约，我同意删除或修改介绍人。',
  'confirmation_terms_1': '(但是，如果有多个推荐人，则直接权利的百分比为用户指定的百分比。）',
  'introducer': '介绍人：',
  'introduced_by': '参与者：',
  'enrollment_data': '入会日期：',
  'crop': '莊稼',
  'please_crop_image': '請裁切影像',
  'failed_during_cropping_image': '裁剪影像時失敗。',
  'the_image_too_small': '圖片太小.',
  'add_p2u_store_updated_successfully':
  '您的P2U商店已成功更新',
  'grant_location_permission':'请授予定位权限并重新打开屏幕。',
  'p2u_store_deleted_successfully': '商店删除成功。',
  'p2u_store_deleted_unsuccessfully': '无法删除商店。',
  'delete': '删除',
  'undo': '撤消',
  'hide_card_confirm': '您確定要隱藏這張卡嗎？',
  'open_super_save': '進入超級儲存',
  'complete_super_save': '完成超級儲存',
  'request_credit_sale_right': '申請賒銷權',
  'sut_credit_sale_right_issued': 'SUT信用銷售權已到達。',
  'invalid_email_or_id': '电子邮件地址或 ID 不正确',
  'participation_transferred': '转入的参与'
};